issue 92: implement rich text editor
bluewave-labs/bluewave-onboarding pull request #103
Opened 2024-07-13 08:03 UTC by thomastepi

Implement the RichTextEditor component which renders 3 children components:

1. EditorToolbar
2. EditorInput
3. EditorTabs (for switching between editor and preview modes)

2024-07-13 09:09 UTC, erenfn requested changes
Between Editor mode and Preview mode, there are padding and line height differences. Is this expected behavior?

2024-07-13 09:09 UTC, erenfn commented on frontend/src/components/RichTextEditor/Toolbar/EditorToolbar.jsx
> +      <button className="ql-link"></button>
This link button currently does nothing. Should it perform an action?

2024-07-13 09:09 UTC, erenfn commented on frontend/src/scenes/dashboard/Dashboard.jsx
> +        <div style={{ display: "block", width: "fit-content" }}>
remove lines 44-46 after your testing is done

2024-07-13 09:12 UTC, erenfn commented on frontend/src/components/RichTextEditor/RichTextEditor.jsx
> +  width: "500px",
Also don't use defaultProps. Do
` const RichTextEditor = ({ width = '500px' })`

The reason we don't use defaultProps is because we get this warning in the browser:
`Warning: RichTextEditor: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead`

2024-07-14 06:35 UTC, thomastepi commented on frontend/src/components/RichTextEditor/Toolbar/EditorToolbar.jsx
> +      <button className="ql-link"></button>
yes. when clicked a tooltip pops up with an input for the href. fixed the issue.

2024-07-14 06:40 UTC, thomastepi commented
> Between Editor mode and Preview mode, there are padding and line height differences. Is this expected behavior?

yes it is expected behavior because the ReactQuill component editor has inbuilt css while the div that renders preview has none. However, the inbuilt css can be overridden

2024-07-16 14:57 UTC, erenfn approved these changes

2024-07-20 12:21 UTC, uparkalau approved these changes

2024-07-20 22:43 UTC, merged