Feature/issue 105 check box default
bluewave-labs/bluewave-onboarding pull request #109
Opened 2024-07-21 22:14 UTC by SimerdeepSinghGrewal

added default props to Checkbox component.

2024-07-23 04:29 UTC, uparkalau approved these changes

2024-07-23 04:30 UTC, uparkalau approved these changes

2024-07-23 10:49 UTC, erenfn requested changes
Also I think you forgot to create a new branch. Can you create another PR without the changes from the tours PR?

2024-07-23 10:49 UTC, erenfn commented on frontend/src/components/Checkbox/Checkbox.jsx
> +                  sx={{
Can you make this style a variable?

2024-07-23 10:49 UTC, erenfn commented on frontend/src/components/Checkbox/Checkbox.jsx
something like:

  const  sx = {
    color: variant === 'primary' ? 'var(--main-purple)' : '#808080E5',
    '&.Mui-checked': {
      color: variant === 'primary' ? 'var(--main-purple)' : '#808080E5',
    },
    '&.MuiCheckbox-indeterminate': {
      color: variant === 'primary' ? 'var(--main-purple)' : '#808080E5',
    },
  }

2024-07-23 10:49 UTC, erenfn commented on frontend/src/components/Checkbox/Checkbox.jsx
> +            sx={{
then sx={sx}

2024-07-24 22:14 UTC, SimerdeepSinghGrewal commented
> Also I think you forgot to create a new branch. Can you create another PR without the changes from the tours PR?

I did created a new branch "feature/Issue-105-CheckBox-default"

2024-07-24 22:27 UTC, SimerdeepSinghGrewal commented on frontend/src/components/Checkbox/Checkbox.jsx
> +                  sx={{
created a function as it needs to change style for each variant

2024-07-25 18:11 UTC, SimerdeepSinghGrewal commented
> It still has the changes from the other branch. Please remove those.

done

2024-07-26 14:29 UTC, uparkalau submitted a review, later dismissed

2024-07-27 11:58 UTC, erenfn requested changes

2024-07-27 11:58 UTC, erenfn commented on frontend/src/components/ConfirmationPopup/ConfirmationPopup.jsx
> +import React from 'react';
remove this file

2024-07-27 11:58 UTC, erenfn commented on frontend/src/App.jsx
> +        <Route path="/tours" element={<ProductTour />} />
remove this line (27)

2024-07-27 11:58 UTC, erenfn commented on frontend/src/App.jsx
> +import ProductTour from "./scenes/productTour/ProductTour";
remove this line (12)

2024-07-27 21:25 UTC, uparkalau commented
@coderabbitai review PR

2024-07-28 15:58 UTC, uparkalau submitted a review, later dismissed

2024-07-29 19:33 UTC, SimerdeepSinghGrewal commented on frontend/src/components/ConfirmationPopup/ConfirmationPopup.jsx
> +import React from 'react';
I never worked on this component but removing it

2024-08-01 19:01 UTC, uparkalau approved these changes

2024-08-07 17:09 UTC, erenfn requested changes

2024-08-07 17:09 UTC, erenfn commented on frontend/src/components/ConfirmationPopup/ConfirmationPopup.jsx
> +import PropTypes from 'prop-types';
delete this file

2024-08-09 16:46 UTC, SimerdeepSinghGrewal commented on frontend/src/components/ConfirmationPopup/ConfirmationPopup.jsx
> +import PropTypes from 'prop-types';
I never worked on this component

2024-08-09 18:36 UTC, erenfn commented on frontend/src/components/ConfirmationPopup/ConfirmationPopup.jsx
> +import PropTypes from 'prop-types';
Not line 1. Delete the entire file

2024-08-12 15:30 UTC, erenfn approved these changes

2024-08-12 17:48 UTC, merged