feat: [110] add error pages
bluewave-labs/bluewave-onboarding pull request #149
Opened 2024-08-18 21:24 UTC by Cihatata

Issues #110
When I looked at the project, I saw this as an entry-level issue and wanted to do it.

I think page not found(404) and no authorization(403) pages should be separate. They mean different things and the url names should be different. That's why I made it as two different pages. I separated the texts in the design.
<img width="1430" alt="image" src="https://github.com/user-attachments/assets/824244bb-0c11-4e00-b1b6-977a562cedc4">

2024-08-19 23:15 UTC, uparkalau requested changes
It looks good . Could you please add a test using [vitest ](https://vitest.dev/)
It is under test folder frontend\src\tests

2024-08-19 23:18 UTC, erenfn requested changes

2024-08-19 23:18 UTC, erenfn commented on frontend/src/scenes/errors/constant.js
> +export const TEXT_404 = 'The URL doesn’t exist';
constants should be under src/utils folder. scenes folder is just for the pages

2024-08-21 00:12 UTC, Cihatata commented
> It looks good . Could you please add a test using [vitest ](https://vitest.dev/) It is under test folder frontend\src\tests

I added test cases

2024-08-22 11:27 UTC, erenfn submitted a review, later dismissed

2024-08-25 14:09 UTC, Cihatata commented
Is there anything expected from me for this PR?

2024-08-25 14:15 UTC, uparkalau commented
> Is there anything expected from me for this PR?

Yes please delete jest library and use vitest as I requested in previous comment.

2024-08-25 14:21 UTC, uparkalau commented on frontend/vite.config.js
We do not need extra library for this kind of tests, delete setup files , use vitest. https://vitest.dev/guide/

2024-08-25 14:23 UTC, uparkalau requested changes
Please, mark all conversation resolved when you done

2024-08-27 23:25 UTC, uparkalau commented
> Is there anything expected from me for this PR?

How is it going?

2024-08-28 04:14 UTC, Cihatata commented
> > Is there anything expected from me for this PR?
> 
> How is it going?

I got errors with toHaveStyle when I was doing the job, so I added the setupTest file. I'll see if there's a different way.

2024-08-30 07:22 UTC, Cihatata commented
Fixed your comments @uparkalau

2024-08-30 14:09 UTC, erenfn submitted a review, later dismissed
Do git pull from develop and it is good to go

2024-08-30 14:26 UTC, uparkalau commented
IT looks good. Accept new changes from the develop branch and you can merge it.

2024-08-30 14:26 UTC, uparkalau approved these changes

2024-08-30 15:50 UTC, uparkalau approved these changes

2024-08-30 18:40 UTC, Cihatata commented
> Do git pull from develop and it is good to go
updated branch

2024-08-30 19:14 UTC, uparkalau commented
> > It looks good . Could you please add a test using [vitest ](https://vitest.dev/) It is under test folder frontend\src\tests
> 
> I added test cases

Yes, you can merge it.
Thank you.

2024-08-30 21:19 UTC, Cihatata commented
> > > It looks good . Could you please add a test using [vitest ](https://vitest.dev/) It is under test folder frontend\src\tests
> > 
> > 
> > I added test cases
> 
> Yes, you can merge it. Thank you.

Thank you, I am waiting approve from @erenfn

2024-08-30 23:19 UTC, erenfn approved these changes

2024-08-31 06:46 UTC, Cihatata commented
I cant show Merge button I guess I don't have access. Can you merge it?
<img width="770" alt="image" src="https://github.com/user-attachments/assets/d978a693-316f-4091-8fd3-be58aa1404e2">

2024-08-31 13:16 UTC, merged