Feature/issue 75 develop a page for creating new product tour items
bluewave-labs/bluewave-onboarding pull request #164
Opened 2024-08-26 21:25 UTC by SimerdeepSinghGrewal

Just updated the ListItem component's icons from Setting and Delete to Edit and Delete Icons

2024-08-26 22:25 UTC, erenfn requested changes
Don't include changes from the Radiobutton branch. Also always do `git pull origin develop` before pushing your code

2024-08-26 22:26 UTC, erenfn commented
and do not include package lock json

2024-08-26 23:40 UTC, erenfn approved these changes

2024-08-27 14:42 UTC, uparkalau approved these changes

2024-08-27 14:47 UTC, merged