refactored regex validation
bluewave-labs/bluewave-onboarding pull request #170
Opened 2024-08-28 11:50 UTC by VishnuSrivatsava

Refactored the regex validation for models and controllers into guideHelpers.js
this will close the issue #169

2024-08-28 12:07 UTC, erenfn commented on backend/src/models/Banner.js
> +import { validateHexColor, isHexColor } from '../utils/guideHelpers';
change it to this:

const { validateHexColor } = require('../utils/guideHelpers');

2024-08-28 12:08 UTC, erenfn requested changes
change import statements to require:

SyntaxError: Cannot use import statement outside a module

2024-08-28 12:08 UTC, erenfn commented on backend/src/models/Popup.js
> +import { validateHexColor, isHexColor } from '../utils/guideHelpers';
change it to this:

const { validateHexColor } = require('../utils/guideHelpers');

2024-08-28 12:08 UTC, erenfn commented on backend/src/models/Banner.js
> +import { validateHexColor, isHexColor } from '../utils/guideHelpers';
change it to this:

const { validateHexColor } = require('../utils/guideHelpers')

2024-08-28 12:12 UTC, VishnuSrivatsava commented on backend/src/models/Popup.js
> +import { validateHexColor, isHexColor } from '../utils/guideHelpers';
we need both validateHexColor and isHexColor in the code right?

2024-08-28 12:13 UTC, VishnuSrivatsava commented on backend/src/models/Popup.js
> +import { validateHexColor, isHexColor } from '../utils/guideHelpers';
Okay got it, it does a sub-call so it works.

2024-08-28 12:15 UTC, erenfn commented on backend/src/models/Popup.js
> +import { validateHexColor, isHexColor } from '../utils/guideHelpers';
isHexColor is just a boolean check. We already call it inside validateHexColor which returns an Error if validation fails. We use isHexColor in controllers and validateHexColor in models. If you look at your import statement at VS Code it will underline isHexColor as unused in the models part.

2024-08-28 12:17 UTC, VishnuSrivatsava commented on backend/src/models/Popup.js
> +import { validateHexColor, isHexColor } from '../utils/guideHelpers';
yup yup I got it

2024-08-28 12:27 UTC, VishnuSrivatsava commented
@erenfn also are there any internship/job (remote) opportunities? Would love to work on some interesting issues.

2024-08-28 12:39 UTC, erenfn commented
@gorkem-bwl

2024-08-28 17:27 UTC, gorkem-bwl commented
> @erenfn also are there any internship/job (remote) opportunities? Would love to work on some interesting issues.

Currently we don't, but will let you know once there is one. Until that time feel free to contribute to the repo. Thank you!

2024-08-28 17:48 UTC, merged

2024-08-29 01:26 UTC, VishnuSrivatsava commented
> > @erenfn also are there any internship/job (remote) opportunities? Would love to work on some interesting issues.
> 
> Currently we don't, but will let you know once there is one. Until that time feel free to contribute to the repo. Thank you!

Thank you! Will contribute in my free time.