add surname field on signup page
bluewave-labs/bluewave-onboarding pull request #184
Opened 2024-09-05 05:20 UTC by mr-loop-1

Replaces the username field with name and surname in the application

2024-09-05 06:12 UTC, mr-loop-1 commented
https://github.com/bluewave-labs/bluewave-onboarding/pull/181#discussion_r1744603745

@erenfn I changed username to name and surname in backend too and hence on frontend where it is used.

2024-09-05 13:54 UTC, gorkem-bwl commented
Thank you for your contribution @mr-loop-1

2024-09-05 18:03 UTC, mr-loop-1 commented
@erenfn now I saw your pr but it was closed

2024-09-05 18:43 UTC, uparkalau requested changes
do not delete username from the table

2024-09-05 21:03 UTC, erenfn commented
> @erenfn now I saw your pr but it was closed

It is still open, but you may need to merge it since you made a change afterwards

2024-09-06 04:43 UTC, mr-loop-1 commented
@uparkalau @erenfn do we need username field too with surname and name

2024-09-06 04:45 UTC, uparkalau commented
> > do not delete username from the table
> 
> @uparkalau @erenfn do we need username field too with surname and name

Yes keep username do not delete it

2024-09-06 04:48 UTC, mr-loop-1 commented
> Yes keep username do not delete it

then I guess it would be a unique identifier like email. Btw what would be displayed on Header/dashboard and stored in cookies, the name+surname or username

2024-09-06 05:34 UTC, uparkalau requested changes

2024-09-06 05:34 UTC, uparkalau commented on backend/migrations/20240422214219-create_users_table.js
> +      name: {
This is not the correct way to add new fields to the database. You don't need to change the existing migration; instead, you should create a new migration with the new fields you want to add and remove the field from the table. So, create a new migration. Yes, you can delete the username field. On the frontend, create a function that generates the username from the name and surname, and use this function wherever a username is needed.

2024-09-06 06:12 UTC, mr-loop-1 commented on backend/migrations/20240422214219-create_users_table.js
> +      name: {
Yes, that was an oversight. It was when I wanted to quickly test with name and surname fields I modified the existing, but didn't create new one when pushing.

2024-09-06 06:16 UTC, uparkalau approved these changes

2024-09-06 12:07 UTC, erenfn approved these changes

2024-09-06 12:12 UTC, merged