replace react quill with tiptap editor
bluewave-labs/bluewave-onboarding pull request #197
Opened 2024-09-10 04:41 UTC by thomastepi

replaced quill editor with more stable and well maintained tiptap

2024-09-10 13:14 UTC, erenfn commented on frontend/src/components/Button/Button.jsx
> +  buttonType: PropTypes.oneOf(['primary', 'secondary', 'secondary-grey', 'secondary-purple', 'error'])
Is this a new button style that wasn't present before?

2024-09-12 23:57 UTC, uparkalau approved these changes

2024-09-24 03:52 UTC, uparkalau submitted a review, later dismissed

2024-09-24 03:53 UTC, uparkalau commented on frontend/src/components/Button/Button.jsx
> +  buttonType: PropTypes.oneOf(['primary', 'secondary', 'secondary-grey', 'secondary-purple', 'error'])
@thomastepi please double check button options

2024-10-01 13:21 UTC, uparkalau commented on frontend/package.json
> +    "@testing-library/jest-dom": "^5.17.0",
please delete @testing-library/jest-dom".
We do not need this.

2024-10-03 22:01 UTC, erenfn requested changes
Take a look at Vlad's comments

2024-10-08 14:15 UTC, thomastepi commented on frontend/src/components/Button/Button.jsx
> +  buttonType: PropTypes.oneOf(['primary', 'secondary', 'secondary-grey', 'secondary-purple', 'error'])
i needed to use this button-disable style present in the button css file: /* .secondary-disabled */
.secondary.MuiButton-root:disabled {
  color: grey;
  background-color: white;
  border-color: #80808033;
  font-weight: 600;
}

2024-10-12 23:41 UTC, erenfn approved these changes

2024-10-12 23:41 UTC, merged