Settings and Teams feature
bluewave-labs/bluewave-onboarding pull request #211
Opened 2024-09-16 06:28 UTC by mr-loop-1

2024-09-16 23:23 UTC, erenfn requested changes

2024-09-16 23:23 UTC, erenfn commented on backend/migrations/20240916052017-create_teams_table.js
> +
This is not the correct way to create the table. Create the table like the others in the models folder, and add it to the index.js file, as done with the others.

2024-09-16 23:23 UTC, erenfn commented on backend/src/controllers/user.controller.js
> +const updateUserDetails = async (req, res) => {
Do not include database logic (such as User.findByPk) in the controller file. This file is meant only for checking incoming data. All database operations, like User.findByPk, should be done in the services file. Refer to other flows, such as the files for banners, for guidance.

Take a look at MVCS architecture

2024-09-16 23:27 UTC, erenfn commented on backend/.env
> -# Node environment
Also this can stay here for now. It allows our tests to run. We'll remove this soon

2024-09-17 02:28 UTC, mr-loop-1 commented on backend/migrations/20240916052017-create_teams_table.js
> +
ok I will do that, I haven started yet on this.

2024-09-17 02:29 UTC, mr-loop-1 commented on backend/src/controllers/user.controller.js
> +const updateUserDetails = async (req, res) => {
Ok I will create a user service. I was looking at other controllers of this file which had queries, will move them to service as well.

2024-09-17 16:21 UTC, mr-loop-1 commented on backend/.env
> -# Node environment
ok, I will add it again at end of all work right before merge. this will allow me to not have to modify it before every commit.

2024-09-17 16:34 UTC, mr-loop-1 commented on backend/.env
> -# Node environment
btw there is another [.env](https://github.com/bluewave-labs/bluewave-onboarding/blob/develop/.env) at root folder, the one I removed is in backend folder

2024-09-20 20:24 UTC, erenfn commented
> @erenfn I am starting further work on this PR
> 
> this line is in both dev and master branch,
> 
> https://github.com/bluewave-labs/bluewave-onboarding/blob/d97a7a8229d54a17d01d5c812fd3f4441f6d7e87/backend/index.js#L34-L36
> 
> this is making my db clear out after every server start

Try `alter: true` but there are also some problems with it. It is up to you

2024-09-20 20:26 UTC, erenfn commented on backend/src/models/UserTeams.js
> +module.exports = (sequelize, DataTypes) => {
You don't need this table, it is redundant. You can keep role and  teamId in user table.

2024-09-20 20:29 UTC, erenfn commented on backend/src/models/Team.js
> +module.exports = (sequelize, DataTypes) => {
This table is also redundant right now. The only useful feature here is the Team Name, and we can store it instead of teamId in other tables.

2024-09-21 05:10 UTC, mr-loop-1 commented on backend/src/models/UserTeams.js
> +module.exports = (sequelize, DataTypes) => {
I made these more modular so that features like changing teams, as well as choosing invites and multi-team feature can be added later on. I will mark this pr for review soon.

2024-09-21 12:16 UTC, erenfn commented on backend/src/models/UserTeams.js
> +module.exports = (sequelize, DataTypes) => {
@uparkalau Can you take a look at this?

2024-09-21 14:18 UTC, mr-loop-1 commented on backend/index.js
> +// sequelize
will restore this

2024-09-21 17:05 UTC, mr-loop-1 commented
@erenfn @uparkalau 
The reason I separated team and user is because the application in itself is in context of team (or organisation) and the biggest effect is that multiple users belong to same team.
So, multiple users are logging in to the same context, and hence if I change, say, team name for one user then it has to be for every other one. As per above comment, in absence of teams table, it would mean updating all users.

2024-09-21 17:30 UTC, mr-loop-1 commented
@erenfn @uparkalau @gorkem-bwl 

I have implemented all the services required according to current designs, as well as routes and controllers needed, although commented some as they are not needed right now and can remove them too.

I added a checklist above in description and It would be helpful if we can be on the same page regarding the overall logic flow before I spend time on the next points. I am happy to answer any comments/doubts/reasoning behind the code.

2024-09-21 17:52 UTC, mr-loop-1 commented
A few additional points to consider
- whether to soft delete or hard delete a user account
- who can send invite - admin only or anyone in the team
- if there are multiple invites to an email, then after signup from that email, whether first or last invite to be considered

2024-09-21 18:24 UTC, mr-loop-1 commented on backend/migrations/20240906060143-add-name-surname-to-users.js
> -      allowNull: false,
it is causing problems in undo

2024-09-22 15:50 UTC, gorkem-bwl commented
> A few additional points to consider
> 
> * whether to soft delete or hard delete a user account
> * who can send invite - admin only or anyone in the team
> * if there are multiple invites to an email, then after signup from that email, whether first or last invite to be considered

Thanks for those comments. Here are the answers.

1. When a user account is removed, it is hard deleted. All the user information should be purged from the database, including user's name, surname, hashes, and anything related. There should be no PII left in the DB.

2. Only an admin can send an invite. 

3. If there are multiple invites to an email, the last invite can invalidate the previous one, and only the last invite should be valid. In the case of an invalid invite, we can mention this in the login page as "This invitation is invalid", which also would cover wrong invitation codes.

2024-09-22 15:52 UTC, gorkem-bwl commented
> @erenfn @uparkalau @gorkem-bwl
> 
> I have implemented all the services required according to current designs, as well as routes and controllers needed, although commented some as they are not needed right now and can remove them too.
> 
> I added a checklist above in description and It would be helpful if we can be on the same page regarding the overall logic flow before I spend time on the next points. I am happy to answer any comments/doubts/reasoning behind the code.

WRT the checklist above - can you provide inputs @erenfn / @VladimirParkalov ?

2024-09-22 16:05 UTC, mr-loop-1 commented
Thanks @gorkem-bwl ,
For point no. 3, is there an invitation code planned on sign up page which is not in designs. Currently, I am having the new user join the last team invite they got on email, or create a default new team for them as admin if there is no invite.

2024-09-23 02:19 UTC, gorkem-bwl commented
> Thanks @gorkem-bwl ,
> 
> For point no. 3, is there an invitation code planned on sign up page which is not in designs. Currently, I am having the new user join the last team invite they got on email, or create a default new team for them as admin if there is no invite.
> 
> btw the checklist was to track what's done on this pr till now and what's left.

The signup page is only visible when the deployment is done. 

Let me explain. The basic rule of thumb is that, this application is not designed to have a multi-tenant system, but rather deployed on a server. When it is deployed, the first sign up page is shown which is supposed to be filled in by the admin (name, surname, email and password), and then this page will be invisible. 

This ensures that the first signed up person is the admin, and the admin can invite others to sign up. It is not possible for anyone to signup without an invitation. 

Regarding your last sentence: There should be only 1 team, and under no circumstances, the system would create another team. 

Let me know if there is anything unclear.

2024-09-23 04:46 UTC, mr-loop-1 commented
@gorkem-bwl , so it is one app or organisation per deployment.

2024-09-23 16:18 UTC, gorkem-bwl commented
> @gorkem-bwl , so it is one app or organisation per deployment (of server and db). I will update the code soon

Sorry for the late answer. This app is supposed to be deployed on a server, which is supposed to run only for one organization.

2024-09-23 16:38 UTC, mr-loop-1 commented
@gorkem-bwl thanks for clearing the logical flow.

2024-09-27 19:51 UTC, mr-loop-1 commented
@gorkem-bwl 
I was able to get some time today and changed the logic. I have a few points
- can an admin remove themselves from team
- what happens to team and admin role when the current admin deletes their account
- can there me more than one admin at same time. If yes, can this admin remove other admins

- I noticed that there is a down-arrow selector on role column of team members in figma, does that mean that roles can be changed?

@erenfn @uparkalau
I also wanted to know how should the initialisation of admin happen. My take is a seeder with values of username and password from config or otherwise default.

2024-09-28 00:30 UTC, gorkem-bwl commented
Thanks for those questions. My answers are inline.

> @gorkem-bwl I was able to get some time today and changed the logic. I have a few points
> 
> * can an admin remove themselves from team

No, admin shouldn't be able to remove themselves from the team. In the future, as long as another admin is present, any  admin should be able to remove themselves.

> * what happens to team and admin role when the current admin deletes their account

The current admin shouldn't be able to delete their account. 

> * can there be more than one admin at same time. If yes, can this admin remove other admins

Yes, there can be more than one admin. An admin can add other admins. An admin can remove other admins.

> * I noticed that there is a down-arrow selector on role column of team members in figma, does that mean that roles can be changed?

Yes, it is a way to change a role. When the drop down selector is clicked, the admin is able to select another auth level for that user. Note that the change shouldn't be instantaneous - it requires the 'Save' button to be clicked afterwards. When the save button is clicked, we better show a notification that this action succeeded (Successfully changed the authorization level). 

Afterwards, the user whose auth level changed should be logging out and logging in to see the changes.

2024-09-29 15:51 UTC, mr-loop-1 commented
Hi @gorkem-bwl @erenfn @uparkalau 
the pr is ready for review. This now fulfils most of the discussion we've had and the designs too.

The thing not implemented yet is error messages in response when some error occurs where I would need your help after the main logic is approved.

2024-09-30 14:38 UTC, gorkem-bwl commented
> Hi @gorkem-bwl @erenfn @uparkalau the pr is ready for review. This now fulfils most of the discussion we've had and the designs too.
> 
> The thing not implemented yet is error messages in response when some error occurs where I would need your help after the main logic is approved.

Do you have some sort of UI you can show? (eg video?)

2024-09-30 15:19 UTC, mr-loop-1 commented
@gorkem-bwl The frontend is not there yet for these changes, I can give a list of features/changes.

2024-09-30 15:29 UTC, gorkem-bwl commented
> @gorkem-bwl The frontend is not there yet for these changes, I can give a list of features/changes.

Ah ok - nevermind then ;)

2024-10-03 21:56 UTC, erenfn requested changes
Can you share the requests (if you used Postman, the Postman collection) you used to test the endpoints?

2024-10-03 21:56 UTC, erenfn commented on backend/index.js
> +// sequelize
please uncomment this

2024-10-03 21:56 UTC, erenfn commented on backend/src/controllers/invite.controller.js
> +    console.log("🚀 ~ sendTeamInvite ~ error:", error)
use our Custom Toast notifications

2024-10-03 21:56 UTC, erenfn commented on backend/src/controllers/team.controller.js
> +    const { name } = req.body;
add type check

2024-10-03 21:56 UTC, erenfn commented on backend/src/controllers/team.controller.js
> +  const { memberId } = req.body;
add type check

2024-10-03 21:56 UTC, erenfn commented on backend/src/controllers/user.controller.js
> +    await user.update({
Can you move this part to service?

2024-10-03 21:59 UTC, erenfn commented
> > @gorkem-bwl , so it is one app or organisation per deployment (of server and db). I will update the code soon
> 
> Sorry for the late answer. This app is supposed to be deployed on a server, which is supposed to run only for one organization.

As Gorkem mentioned, the app is currently designed to be used by a single organization, so the Team table doesn't serve a meaningful purpose at the moment. I'm not sure if we plan to extend the scope to support multiple teams in the future. If we do, this table could become useful, but it's unclear whether that will happen. @gorkem-bwl @uparkalau what do you think?

2024-10-03 22:01 UTC, gorkem-bwl commented
The team table is supposed to show a list of users in the team. Yes, there is only one team, however it can also have multiple users. That is the reason the team table is there.

2024-10-03 22:04 UTC, erenfn commented
> The team table is supposed to show a list of users in the team. Yes, there is only one team, however it can also have multiple users. That is the reason the team table is there.

We have 'Users' table which shows the list of the users. It is not team specific as we only have one team. Right now the team table only stores team name

> const Team = sequelize.define(
      "Team",
      {
        id: {
          type: DataTypes.INTEGER,
          primaryKey: true,
          autoIncrement: true,
        },
        name: {
          type: DataTypes.STRING(50),
          allowNull: false,
        },
        createdAt: {
          type: DataTypes.DATE,
          allowNull: false,
          defaultValue: DataTypes.NOW,
        },
      },

2024-10-03 22:11 UTC, gorkem-bwl commented
Right, I think we are good to go in this scenario!

2024-10-04 02:53 UTC, mr-loop-1 commented
@erenfn 
To store the single value of team name in db, I thought about two options, `teams` table with a single row or `configs` key-value table with a teamName key. 
I choose first for simplicity, can also go with other one or something you could suggest.

2024-10-04 12:22 UTC, erenfn commented
> @erenfn To store the single value of team name in db, I thought about two options, `teams` table with a single row or `configs` key-value table with a teamName key. I choose first for simplicity, can also go with other one or something you could suggest.

Okay, I think it is fine for now. Can you share your Postman collection (if any) so that I can test the endpoints?

2024-10-04 13:39 UTC, mr-loop-1 commented
@erenfn I was away, will share soon.

2024-10-04 13:53 UTC, uparkalau commented on backend/src/service/user.service.js
> +const settings = require("../../config/settings");
Review all constant, leave only that you are using. Double check if file name has a space, like user .service.js

2024-10-04 13:58 UTC, uparkalau commented on backend/src/controllers/invite.controller.js
> +    console.log("🚀 ~ sendTeamInvite ~ error:", error)
What is a rocket icon?

2024-10-04 14:56 UTC, uparkalau submitted a review, later dismissed
Please review coderabbit refactoring suggestions and implement that really makes sense.

2024-10-05 10:52 UTC, mr-loop-1 commented
@erenfn 
https://api.postman.com/collections/38807808-03f17c08-2558-4273-a996-c0d3454b768f?access_key=PMAT-01J9E4W1E1CWM3CY6NAEZ2QZTR

2024-10-05 10:54 UTC, mr-loop-1 commented on backend/src/controllers/invite.controller.js
> +    console.log("🚀 ~ sendTeamInvite ~ error:", error)
This is for debugging, as I mentioned the error messages are not done yet

2024-10-05 11:04 UTC, mr-loop-1 commented
@erenfn 
https://api.postman.com/collections/38807808-03f17c08-2558-4273-a996-c0d3454b768f?access_key=PMAT-01J9E5M1VD8VF8GN36GXAFHGXR

2024-10-05 12:33 UTC, mr-loop-1 commented
@erenfn @uparkalau @gorkem-bwl 
There were some suggestions regarding validating the incoming request params/body. 
This is something I was aware of while coding too but didn't do that as I think this should be done through validating middleware/dto by some lib like `express-validator`. The reason being validations such as userId, user's name etc are repeated across controllers and would be heavily duplicated.

We can add them now like done in Banner and Popup controllers if required, **or** leave as it is and create a new issue to add a validating system to the app.

2024-10-05 16:25 UTC, mr-loop-1 commented
> @erenfn @uparkalau @gorkem-bwl There were some suggestions regarding validating the incoming request params/body. This is something I was aware of while coding too but didn't do that as I think this should be done through validating middleware/dto by some lib like `express-validator`. The reason being validations such as userId, user's name etc are repeated across controllers and would be heavily duplicated.
> 
> We can add them now like done in Banner and Popup controllers if required, **or** leave as it is and create a new issue to add a validating system to the app.

Alongside, we can now address the error responses. I delayed because I was unsure if use the `src/utils/error.js` file or do directly. There is an argument called `errorCode` which is passed as below.

https://github.com/bluewave-labs/bluewave-onboarding/blob/e302238b01aadfdafe6c505c7ae79fe226619ecc/backend/src/utils/errors.js#L22
https://github.com/bluewave-labs/bluewave-onboarding/blob/e302238b01aadfdafe6c505c7ae79fe226619ecc/backend/src/controllers/popup.controller.js#L64-L66
I wanted to know if this is how it is supposed to be done. I can then map error codes with error messages.

2024-10-06 02:29 UTC, gorkem-bwl commented
Sure, we can discuss. Do you have a specific question here for me?

2024-10-06 11:03 UTC, mr-loop-1 commented
@gorkem-bwl I wanted to know what is meant by signup page getting invisible. Because even if a user is invited, it is through mail, and we still need name and password and hence require signup. and where does invite code fits in all this.

2024-10-06 14:26 UTC, gorkem-bwl commented
> @gorkem-bwl I wanted to know what is meant by signup page getting invisible. Because even if a user is invited, it is through mail, and we still need name and password and hence require signup. and where does invite code fits in all this.

Sure, let me explain. The initial signup page and the signup page that is shown after an invite are totally different in terms of what they serve.

- **Initial signup page:** This is only for admins, and will be shown only once to the user who deploys the system. It won't be visible afterwards and will never be used again. 
- **Invitation signup page:** When an invitation is initiated by the admin, the user gets and email, and this page is shown. This is an invite only signup page, and will be shown to everyone who gets an invite by the admin. 

Is it more clear now? Let me know if you need more info and/or anything is not clear.

2024-10-07 11:03 UTC, mr-loop-1 commented
@erenfn @uparkalau 
any inputs/approach

2024-10-07 11:25 UTC, erenfn requested changes

2024-10-07 11:29 UTC, erenfn commented
> @erenfn @uparkalau @gorkem-bwl There were some suggestions regarding validating the incoming request params/body. This is something I was aware of while coding too but didn't do that as I think this should be done through validating middleware/dto by some lib like `express-validator`. The reason being validations such as userId, user's name etc are repeated across controllers and would be heavily duplicated.
> 
> We can add them now like done in Banner and Popup controllers if required, **or** leave as it is and create a new issue to add a validating system to the app.

Sure I'll create a new issue for it

2024-10-07 13:44 UTC, erenfn commented on backend/src/controllers/team.controller.js
> +  const { memberId, role } = req.body;
Oh, okay. But the middleware still needs to check that the role of the executor is admin. Currently, I don't see any check for that.

2024-10-08 10:32 UTC, erenfn commented on backend/src/controllers/team.controller.js
> +  const { memberId, role } = req.body;
const user = await User.findOne({
                where: {id: userId}
            });
            if(!settings.team.removeUser.includes(user.role)) {
                throw new Error("User not authorized to delete this user");
            }

This part creates repetition. It's better to create a separate middleware within authMiddleware. This will make the code cleaner and prevent unnecessary calls to the controller if the user is not an admin.

2024-10-10 11:26 UTC, erenfn commented on backend/src/controllers/team.controller.js
> +  const { memberId, role } = req.body;
> Each route may have different set of valid roles, hence we can provide this array as a callback to the common middleware. IMO, we should handle this in the validation pr since that is also related to middleware.

That middleware will be separate from the authMiddleware. I see no issue with creating the admin role within the authMiddleware in this PR, as this is the PR where we are implementing the admin role. As I mentioned, it is a better practice to check authorization in the middleware rather than in the service. Therefore, it would be better if you could refactor that in this PR.

2024-10-10 11:31 UTC, erenfn commented on backend/src/controllers/team.controller.js
> +  const { memberId, role } = req.body;
> Can you provide some insights on Gorkem's comment above regarding Initial signup page etc. I think the code would be highly opinionated and best if we can discuss beforehand how to proceed. We can even have a separate pr as that is more on frontend side.

I think he is saying that once this app is installed on the server, it will only allow a single signup for the admin (using our current signup page). After the admin signs up, we should disable this signup page.

What I also understood is that we will create a new signup page for members who receive an invite.

However, this issue is not related to this PR, so we can skip it for now.

2024-10-10 13:34 UTC, gorkem-bwl commented on backend/src/controllers/team.controller.js
> +  const { memberId, role } = req.body;
> > Can you provide some insights on Gorkem's comment above regarding Initial signup page etc. I think the code would be highly opinionated and best if we can discuss beforehand how to proceed. We can even have a separate pr as that is more on frontend side.
> 
> I think he is saying that once this app is installed on the server, it will only allow a single signup for the admin (using our current signup page). After the admin signs up, we should disable this signup page.
> 
> What I also understood is that we will create a new signup page for members who receive an invite.
> 
> However, this issue is not related to this PR, so we can skip it for now.

Exactly this.

2024-10-12 01:23 UTC, uparkalau commented on backend/src/routes/team.routes.js
> +router.post("/invite", authenticateJWT, sendTeamInvite);
if we do update use PUT. For new records use POST

2024-10-12 03:38 UTC, mr-loop-1 commented on backend/src/routes/team.routes.js
> +router.post("/invite", authenticateJWT, sendTeamInvite);
a separate pr was created for this recently

2024-10-12 09:00 UTC, mr-loop-1 commented
Its up for review now @erenfn @uparkalau

2024-10-12 12:55 UTC, erenfn commented on backend/src/middleware/auth.middleware.js
> +    const user = await User.findOne({ where: {id: decoded.id } })
Why did you have to change this?

2024-10-12 12:58 UTC, erenfn commented on backend/src/middleware/accessGuard.middleware.js
> +    }
Why did you mark this as resolved?  I think it is a reasonable suggestion

2024-10-12 12:58 UTC, erenfn commented on backend/src/controllers/team.controller.js
> +};
this too

2024-10-12 13:06 UTC, erenfn commented on backend/src/service/team.service.js
> +            await User.destroy({
It is better to first check if the user exists before deleting them. Handling the case where the user doesn't exist in the catch block isn't the optimal approach

2024-10-12 13:06 UTC, erenfn commented on backend/src/controllers/team.controller.js
> +    await teamService.updateUserRole(userId, memberId, role);
Are you checking whether the input role is indeed a valid role and not something else?

2024-10-12 13:06 UTC, erenfn commented on backend/src/controllers/user.controller.js
> +}
this too

2024-10-12 13:11 UTC, erenfn commented on backend/src/controllers/auth.controller.js
> +    }
this might be also useful

2024-10-12 13:12 UTC, erenfn commented on backend/src/routes/team.routes.js
> +router.delete("/remove", authenticateJWT, accessGuard(teamPermissions.removeUser), removeMember);
this too

2024-10-12 13:18 UTC, mr-loop-1 commented on backend/src/middleware/accessGuard.middleware.js
> +    }
I already did the changes locally, didnt push yet as the bot will again flood will comments.

2024-10-12 13:23 UTC, mr-loop-1 commented on backend/src/controllers/team.controller.js
> +};
did it

2024-10-12 13:24 UTC, mr-loop-1 commented on backend/src/controllers/team.controller.js
> +};
2 and 3 are done. 1st tbd in validation pr.

2024-10-12 13:26 UTC, mr-loop-1 commented on backend/src/controllers/user.controller.js
> +}
I think update shouldn't be the one to return the new user object as frontend's auth provider will only call current-user api.

2024-10-12 13:28 UTC, mr-loop-1 commented on backend/src/controllers/auth.controller.js
> +    }
did the 1st suggestion. transaction is not needed for else block as it is single independent call

2024-10-12 13:30 UTC, mr-loop-1 commented on backend/src/middleware/auth.middleware.js
> +    const user = await User.findOne({ where: {id: decoded.id } })
accessGuard middleware needs role of user to check if user is authorized for the action. We can't put role in jwt as it may have changed in between.

2024-10-12 13:31 UTC, mr-loop-1 commented on backend/src/service/team.service.js
> +            await User.destroy({
the auth middleware first fetchs the user so controller is called only if it exists

2024-10-12 13:31 UTC, mr-loop-1 commented on backend/src/controllers/team.controller.js
> +    await teamService.updateUserRole(userId, memberId, role);
that would be for the validator Pr to implement.

2024-10-12 13:33 UTC, mr-loop-1 commented on backend/src/routes/team.routes.js
> +router.delete("/remove", authenticateJWT, accessGuard(teamPermissions.removeUser), removeMember);
member id would be in body as anybody can attempt to call the route on anybody.

2024-10-12 13:36 UTC, mr-loop-1 commented on backend/src/controllers/user.controller.js
> +}
The function in that will refresh the user object in frontend will always call normal current-user api. So, returning new user is unnecessary here. We only need the success message for Toast notification,

2024-10-12 13:37 UTC, erenfn commented on backend/src/service/team.service.js
> +            await User.destroy({
But isn't this a different user? The auth middleware only checks if the user is the one deleting it, not the user being deleted.

2024-10-12 13:38 UTC, erenfn commented on backend/src/middleware/auth.middleware.js
> +    const user = await User.findOne({ where: {id: decoded.id } })
What I was trying to say is that as far as I can remember `decoded` is already the user. So doing `const user = await User.findOne({ where: {id: decoded.id } })` may be redundant. We may have to double check it

2024-10-12 13:55 UTC, mr-loop-1 commented on backend/src/middleware/auth.middleware.js
> +    const user = await User.findOne({ where: {id: decoded.id } })
The decoded contains the jwt payload that we supplied during login/signup. It is id and email. For role I mentioned it could be outdated so can't take from there.

2024-10-12 13:57 UTC, mr-loop-1 commented on backend/src/service/team.service.js
> +            await User.destroy({
Oh yes, overlooked that.

2024-10-12 14:27 UTC, erenfn commented on backend/src/routes/team.routes.js
> +router.delete("/remove", authenticateJWT, accessGuard(teamPermissions.removeUser), removeMember);
Okay, makes sense

2024-10-12 15:01 UTC, mr-loop-1 commented
@erenfn I did the changes.

2024-10-12 18:48 UTC, erenfn commented on backend/src/controllers/team.controller.js
> +};
it is still not pushed

2024-10-12 18:49 UTC, erenfn commented on backend/src/middleware/accessGuard.middleware.js
>      if(!permissions.includes(req.user.role)) {
make this
 if(!req.user || !permissions.includes(req.user.role)) {

2024-10-12 18:55 UTC, erenfn commented on backend/src/controllers/auth.controller.js
> +      }
This suggestion was also crucial. We shouldn't throw any errors; it crashed the server.

2024-10-12 18:56 UTC, erenfn commented on backend/src/controllers/auth.controller.js
> +        throw new Error("Error registering user by invite");
same here don't throw an error

2024-10-12 19:05 UTC, mr-loop-1 commented on backend/src/controllers/team.controller.js
> +};
I did it. The link here is not updated.

2024-10-12 19:09 UTC, mr-loop-1 commented on backend/src/controllers/auth.controller.js
> +      }
I will change it. But it shouldn't have crashed the server.

2024-10-12 19:13 UTC, erenfn reviewed
i get 

```
{
    "error": "User does not have required access level"
}

```
Although I am the first user

```
"user": {
        "id": 1,
        "name": "new_user23",
        "surname": "name",
        "email": "new_user23@example.com"
    },
```

2024-10-12 19:15 UTC, erenfn commented on backend/src/controllers/auth.controller.js
> +    if(userCount) {
i get 

```
{
    "error": "User does not have required access level"
}

```
Although I am the first user

```
"user": {
        "id": 1,
        "name": "new_user23",
        "surname": "name",
        "email": "new_user23@example.com"
    },
```

Check the login here

2024-10-12 19:16 UTC, mr-loop-1 commented on backend/src/controllers/auth.controller.js
> +    if(userCount) {
on which api?

2024-10-12 19:22 UTC, erenfn commented on backend/src/service/user.service.js
> +    async deleteUser(userId) {
Also I get this responese when I try to delete myself as the admin with 1 userCount:

`{
    "error": "Internal Server Error",
    "message": "Error deleting user ~ relation \"invites\" does not exist",
    "errorCode": "DELETE_USER_ERROR"
}`

2024-10-12 19:22 UTC, erenfn commented
After making these changes, please test your endpoints again. Testing is really really really important

2024-10-12 19:23 UTC, mr-loop-1 commented on backend/src/service/user.service.js
> +    async deleteUser(userId) {
Did you do the migration

2024-10-12 19:24 UTC, mr-loop-1 commented
> After making these changes, please test your endpoints again. Testing is really really really important

I did test all of them before pushing

2024-10-12 19:46 UTC, erenfn commented
> > i get
> > ```
> > {
> >     "error": "User does not have required access level"
> > }
> > ```
> 
> btw on which api call are you getting this error. I can check if this is a bug that got through

At every endpoint that requests 'admin' role.

2024-10-12 19:52 UTC, erenfn commented on backend/src/service/user.service.js
> +    async deleteUser(userId) {
I did this using Sequelize sync. I think the reason we are seeing this issue is not due to migration but because we don't have an initial invite for the first user.

I believe this is related to the previous issue. I registered as the first user, but my role is 'member' and I don't have an invite. I think this should be corrected by registering this user as an admin.

In fact, right now, I think we should register all users as admins. We'll change that later.

2024-10-12 20:03 UTC, mr-loop-1 commented
> I did this using Sequelize sync. I think the reason we are seeing this issue is not due to migration but because we don't have an initial invite for the first user.

but why do we need this sync. i read it is not recommended for production.

2024-10-12 20:14 UTC, erenfn commented
> > I did this using Sequelize sync. I think the reason we are seeing this issue is not due to migration but because we don't have an initial invite for the first user.
> 
> ok, but why do we need this sync.

we don't need it is just an easy way to migrate

2024-10-13 01:23 UTC, gorkem-bwl commented on backend/src/service/user.service.js
> +    async deleteUser(userId) {
> I did this using Sequelize sync. I think the reason we are seeing this issue is not due to migration but because we don't have an initial invite for the first user.
> 
> I believe this is related to the previous issue. I registered as the first user, but my role is 'member' and I don't have an invite. I think this should be corrected by registering this user as an admin.
> 
> In fact, right now, I think we should register all users as admins. We'll change that later.

This is fine.

2024-10-13 23:37 UTC, erenfn commented
I think the problem is in middleware:
When I register I can see that my role is now admin. But I still get `"error": "User does not have required access level"` whenever I try to call an admin endpoint

2024-10-13 23:43 UTC, erenfn commented
Also when I run the code with sequelize sync I get this:

`bluewave-onboarding-db-1                  | 2024-10-13 23:41:00.109 UTC [36] ERROR:  syntax error at or near "1" at character 106
bluewave-onboarding-db-1                  | 2024-10-13 23:41:00.109 UTC [36] STATEMENT:  DROP TYPE IF EXISTS "public"."enum_users_role"; DO 'BEGIN CREATE TYPE "public"."enum_users_role" AS ENUM(1, 2); EXCEPTION WHEN duplicate_object THEN null; END';`

which indicates that there is an issue with the role enum in the constants.js

2024-10-14 00:39 UTC, erenfn commented
When I run with migrations, all of the endpoints work. 

I guess there is a discrepancy between the code and the migrations files

2024-10-14 15:29 UTC, erenfn approved these changes

2024-10-14 15:30 UTC, erenfn approved these changes
Now it works

2024-10-14 15:35 UTC, merged