#5 Implemented table with search and pagination, date picker, tabs
bluewave-labs/bluewave-onboarding pull request #22
Opened 2024-05-07 00:13 UTC by SimerdeepSinghGrewal

I've added tabs and table as per the requirement and figma design. For date picker, I've added two calendars to select date range but I was not sure about the third individual calendar.

2024-05-07 00:27 UTC, gorkem-bwl commented
What is the third individual calendar? @SimerdeepSinghGrewal Can you show a screenshot?

2024-05-07 02:22 UTC, SimerdeepSinghGrewal commented
![Screenshot 2024-05-06 202132](https://github.com/bluewave-labs/bluewave-onboarding/assets/100012027/a80574c6-6a4e-4f80-8ccf-a5786dd8f127)
the one on the right, like 2 calendars on the left and third one right single one

2024-05-07 17:50 UTC, uparkalau commented
Your code looks good, but I would suggest making the folder structure clearer. Please reorganize your code following this example:
/src
  /components
    /Table
      Table.jsx
      TableStyles.css
    /DatePicker
      DatePicker.jsx
      DatePickerStyles.css
    /Tabs
      Tabs.jsx
      TabsStyles.jsx
  index.css // global styles
  App.jsx
  index.js

2024-05-07 20:52 UTC, SimerdeepSinghGrewal commented
> When the button underneath that calendar is clicked



> Ah ok, I should have read that carefully. The one on the right is a single datepicker calendar. When the button underneath that calendar is clicked, corresponding calendar popups up, and the selected date is written on the button.

@gorkem-bwl Just to clarify, the two calendars are not connected, this is a single seperate datepicker calendar and when we click on the button that has the date written on it, the single calendar appears and the date text changes as per the selected date, does that sound correct?

2024-05-07 20:53 UTC, gorkem-bwl commented
That is correct.

2024-05-08 19:50 UTC, uparkalau requested changes

2024-05-11 03:10 UTC, uparkalau approved these changes
Please merge it into develop branch.

2024-05-11 03:12 UTC, uparkalau approved these changes
You can merge it into the develop branch . We will create new task to refactor it.

2024-05-11 03:15 UTC, uparkalau approved these changes

2024-05-11 04:20 UTC, uparkalau submitted a review, later dismissed

2024-05-12 19:03 UTC, uparkalau submitted a review, later dismissed

2024-05-12 19:04 UTC, closed without merging

2024-05-12 20:37 UTC, SimerdeepSinghGrewal commented on frontend/src/components/Tabs/Tabs.jsx
> +const MyTabs = () => {
renamed MyTabs to headingTabs but
using camelCase gives me this error
"[eslint]
src\components\Tabs\Tabs.jsx
  Line 6:29:  React Hook "useState" is called in function "headingTabs" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use"  react-hooks/rules-of-hooks

Search for the keywords to learn more about each error."

2024-05-12 20:37 UTC, SimerdeepSinghGrewal commented on frontend/src/components/Table/TableStyles.css
> +.direct_buttons{
please clarify as I have used css as per the figma designs,