Get rid of top banner
bluewave-labs/bluewave-onboarding pull request #234
Opened 2024-09-25 19:10 UTC by parthmanhas

fixes #153

Changes:

- [x] Get rid of top banner
- [x] Move user profile dropdown to bottom left
- [ ] Move the sidebar up to benefit from the space (didnt understand this)
- [x] Move support link to the bottom of the sidebar menu

HomePage: 
![image](https://github.com/user-attachments/assets/18e84062-b8c6-4efc-82cc-bf1e809868d9)

Tours Page: 
![image](https://github.com/user-attachments/assets/fab67a40-b11a-4539-a0fa-ecdb7a96a7a0)

Hints Page:
![image](https://github.com/user-attachments/assets/917f5985-5154-4d44-a5e8-934620927f6a)

Create Popup page:
![image](https://github.com/user-attachments/assets/4c0a5ed8-4c0f-4abc-ba46-3d4a928f7e14)

Create Banner Page:
![image](https://github.com/user-attachments/assets/43904b2f-4f39-4d3b-9a44-4fd27ee459f4)

Profile Dropdown:
![image](https://github.com/user-attachments/assets/621603ed-2c57-4621-9c06-c0f858357f79)

2024-09-25 20:00 UTC, gorkem-bwl commented
UI wise it looks good. Thank you.

2024-09-25 20:01 UTC, gorkem-bwl commented
>  Move the sidebar up to benefit from the space (didnt understand this)

Probably I meant - if possible, make use of the top space on the sidebar. But from what I see, there is no need and everything is in place, so that subtask is resolved as well.

2024-09-25 22:28 UTC, erenfn requested changes

2024-09-25 22:28 UTC, erenfn commented on frontend/src/components/Logo/LogoStyles.css
> +  margin-top: 1.5rem;
I think margin-top:1rem would be enough

2024-09-25 22:28 UTC, erenfn commented on frontend/src/components/LeftMenu/LeftMenu.jsx
> +      <div className="user-info">
Can you refactor Profile (lines 80-91) as a new component?

2024-09-25 22:28 UTC, erenfn commented on frontend/src/components/LeftMenu/LeftMenu.jsx
>            <ListItemText primary="Support" />
You can add 'Support' to menu-items and then move the Divider (at 72) below support

2024-09-25 22:28 UTC, erenfn commented on frontend/src/components/LeftMenu/LeftMenu.jsx
> +      <Logo isSidebar={true} />
Wrap Logo and List into a div so that space-between only affects the space between the  Divider and the Profile

2024-09-25 22:30 UTC, erenfn commented on frontend/src/templates/HomePageTemplate/HomePageTemplate.css
> +    padding-top: 1.5rem;
I don't think this is necessary, as the goal of removing the header was to create more space.

2024-09-25 22:34 UTC, erenfn commented on frontend/src/components/Logo/LogoStyles.css
> +  margin-top: 1.5rem;
You can also add a bottom margin of about 0.75rem to separate the logo from the buttons.

2024-09-25 22:37 UTC, erenfn reviewed
The changes look good. Only minor styling changes are needed. Other than that, great work!

2024-09-25 22:38 UTC, erenfn commented on frontend/src/scenes/dashboard/Dashboard.module.scss
> +    padding: 1.5rem 3rem;
I think you can also revert this back to just 3rem

2024-09-25 23:16 UTC, erenfn commented
Also don't forget to do `git pull origin develop`. There are some conflicts

2024-09-26 09:54 UTC, Cihatata commented
I think we should css variables for colors. Most hex codes are in the `variabless.css`. Maybe we can replace hex color code with variable

2024-09-26 09:59 UTC, Cihatata commented on frontend/src/scenes/login/ForgotPassword.css
I think we should use css modules for new css files. If it continues to be used in this way, css selector problems may occur in the future.

2024-09-26 17:58 UTC, parthmanhas commented on frontend/src/components/Logo/LogoStyles.css
> +  margin-top: 1.5rem;
addressed in [a779098](https://github.com/bluewave-labs/bluewave-onboarding/pull/234/commits/a779098911204dd949d00793c9c9c0d720735f2f)

2024-09-26 17:58 UTC, parthmanhas commented on frontend/src/components/LeftMenu/LeftMenu.jsx
> +      <div className="user-info">
addressed in [d545e52](https://github.com/bluewave-labs/bluewave-onboarding/pull/234/commits/d545e527a7d2fe809e58cedc2a3047f13ac28120)

2024-09-26 17:58 UTC, parthmanhas commented on frontend/src/components/LeftMenu/LeftMenu.jsx
>            <ListItemText primary="Support" />
addresses in [a8bfff8](https://github.com/bluewave-labs/bluewave-onboarding/pull/234/commits/a8bfff83343c8fb712bb86407862f61da5b50168)

2024-09-26 17:58 UTC, parthmanhas commented on frontend/src/components/LeftMenu/LeftMenu.jsx
> +      <Logo isSidebar={true} />
addressed in [9fed801](https://github.com/bluewave-labs/bluewave-onboarding/pull/234/commits/9fed801c80943b7a2f5943b2682face633b9a96c)

2024-09-26 18:01 UTC, parthmanhas commented on frontend/src/templates/HomePageTemplate/HomePageTemplate.css
> +    padding-top: 1.5rem;
addressed in [19bc4a5](https://github.com/bluewave-labs/bluewave-onboarding/pull/234/commits/19bc4a592cbd77b7883f8f9e47101b5c5c7dd374)

2024-09-26 18:02 UTC, parthmanhas commented on frontend/src/scenes/dashboard/Dashboard.module.scss
> +    padding: 1.5rem 3rem;
addressed in  [2ea41d5](https://github.com/bluewave-labs/bluewave-onboarding/pull/234/commits/2ea41d5819bfe45551d423cfbae5662e8f8c91ef)

2024-09-26 18:57 UTC, parthmanhas commented on frontend/src/scenes/login/ForgotPassword.css
I can do that as part of other pr as this pr already contains many changes. Also I was facing problem doing that to ForgotPassword as the changes to CustomTextField were not reflecting.

2024-09-27 01:02 UTC, erenfn commented on frontend/src/scenes/login/ForgotPassword.css
I am approving and merging this now. I'll create a new issue for this

2024-09-27 01:03 UTC, merged