Issue 78 create new endpoints for managing the tour list
bluewave-labs/bluewave-onboarding pull request #240
Opened 2024-09-27 18:56 UTC by SimerdeepSinghGrewal

Added Tour.js, tour.routes.js, tour.Controller.js, tour.service.js and tour_helper.js

2024-09-27 23:59 UTC, erenfn requested changes

2024-09-27 23:59 UTC, erenfn commented on backend/src/utils/tour_helpers.js
> +const validateTriggeringFrequency = (value) => {
You should use the helper functions in the models 'validate' section. 

For example, replace the validate below with validatePageTargeting. Take a look at #170 if you need a guidance

pageTargeting: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: {
          isIn: [["equals to", "is different from"]],
        },
      },

2024-09-30 16:57 UTC, SimerdeepSinghGrewal commented on backend/src/utils/tour_helpers.js
> +const validateTriggeringFrequency = (value) => {
Done but check the error messages if they are right ?

2024-09-30 19:47 UTC, erenfn requested changes
Did you test your code, and pull from origin?

node:internal/modules/cjs/loader:1251
bluewave-onboarding-onboarding_backend-1  |   throw err;
bluewave-onboarding-onboarding_backend-1  |   ^
bluewave-onboarding-onboarding_backend-1  |
bluewave-onboarding-onboarding_backend-1  | Error: Cannot find module '../utils/tour_helper'
bluewave-onboarding-onboarding_backend-1  | Require stack:
bluewave-onboarding-onboarding_backend-1  | - /app/src/models/Tour.js
bluewave-onboarding-onboarding_backend-1  | - /app/src/models/index.js
bluewave-onboarding-onboarding_backend-1  | - /app/src/controllers/auth.controller.js
bluewave-onboarding-onboarding_backend-1  | - /app/src/routes/auth.routes.js
bluewave-onboarding-onboarding_backend-1  | - /app/index.js
bluewave-onboarding-onboarding_backend-1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
bluewave-onboarding-onboarding_backend-1  |     at Module._load (node:internal/modules/cjs/loader:1074:27)   
bluewave-onboarding-onboarding_backend-1  |     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
bluewave-onboarding-onboarding_backend-1  |     at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)  
bluewave-onboarding-onboarding_backend-1  |     at Module.require (node:internal/modules/cjs/loader:1339:12) 
bluewave-onboarding-onboarding_backend-1  |     at require (node:internal/modules/helpers:135:16)
bluewave-onboarding-onboarding_backend-1  |     at Object.<anonymous> (/app/src/models/Tour.js:5:5)
bluewave-onboarding-onboarding_backend-1  |     at Module._compile (node:internal/modules/cjs/loader:1546:14)
bluewave-onboarding-onboarding_backend-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
bluewave-onboarding-onboarding_backend-1  |     at Module.load (node:internal/modules/cjs/loader:1317:32) {  
bluewave-onboarding-onboarding_backend-1  |   code: 'MODULE_NOT_FOUND',
bluewave-onboarding-onboarding_backend-1  |   requireStack: [
bluewave-onboarding-onboarding_backend-1  |     '/app/src/models/Tour.js',
bluewave-onboarding-onboarding_backend-1  |     '/app/src/models/index.js',
bluewave-onboarding-onboarding_backend-1  |     '/app/src/controllers/auth.controller.js',
bluewave-onboarding-onboarding_backend-1  |     '/app/src/routes/auth.routes.js',
bluewave-onboarding-onboarding_backend-1  |     '/app/index.js'
bluewave-onboarding-onboarding_backend-1  |   ]
bluewave-onboarding-onboarding_backend-1  | }
bluewave-onboarding-onboarding_backend-1  |
bluewave-onboarding-onboarding_backend-1  | Node.js v22.9.0
bluewave-onboarding-onboarding_backend-1  |
bluewave-onboarding-onboarding_backend-1  | [nodemon] app crashed - waiting for file changes before starting.

2024-09-30 19:51 UTC, erenfn commented on backend/src/utils/tour_helpers.js
> +const validateTriggeringFrequency = (value) => {
They are fine

2024-10-12 23:53 UTC, erenfn approved these changes

2024-10-12 23:59 UTC, erenfn commented
Now ready to merge. I fixed the 'tour_helper' import to 'tour_helpers' in Tour.js and changed popup_log to popupLog in index.js (I guess the develop branch wasn't merged correctly).

2024-10-13 18:43 UTC, merged