Fix for Left Menu isn't visible
bluewave-labs/bluewave-onboarding pull request #258
Opened 2024-10-01 08:20 UTC by prashant-80

<img width="1355" alt="Screenshot 2024-10-01 at 1 14 28 PM" src="https://github.com/user-attachments/assets/b1b9b50a-4885-42ce-99c6-5bf6f6e1cf1e">
<img width="1355" alt="Screenshot 2024-10-01 at 1 14 03 PM" src="https://github.com/user-attachments/assets/d9aaebf4-c5bd-4665-8db5-1a59b3a81ea1">

2024-10-01 08:32 UTC, prashant-80 commented on frontend/src/components/LeftMenu/LeftMenu.css
> +  height: 100vh;
fixed it

2024-10-02 23:58 UTC, erenfn commented
@gorkem-bwl 

![image](https://github.com/user-attachments/assets/cc4eba8f-da6e-4c4e-85d6-6d7fcb9d9b08)

I think there is too much space between the profile and the buttons

2024-10-03 11:41 UTC, prashant-80 commented
I adjusted the pixels can you check if it's fine?
<img width="1432" alt="Screenshot 2024-10-03 at 5 07 26 PM" src="https://github.com/user-attachments/assets/1e0c0a42-8f5f-4c77-9493-ca4f1d2077cc">
<img width="1440" alt="Screenshot 2024-10-03 at 4 40 18 PM" src="https://github.com/user-attachments/assets/c6159dc4-7256-4f1a-98cf-ff73a37c6d5a">

2024-10-03 22:50 UTC, erenfn requested changes

2024-10-03 22:50 UTC, erenfn commented on frontend/src/components/LeftMenu/LeftMenu.css
> +  .search-item {
Pull the latest code from develop. We don't have search-item class anymore.

2024-10-03 22:50 UTC, erenfn commented on frontend/src/components/LeftMenu/LeftMenu.css
> +    font-size: 12px;
Don't forget to resize the icons too.

2024-10-04 02:23 UTC, gorkem-bwl approved these changes
Looks better!

2024-10-04 03:39 UTC, prashant-80 commented on frontend/src/components/LeftMenu/LeftMenu.css
> +    font-size: 12px;
I adjusted it

2024-10-04 03:40 UTC, prashant-80 commented on frontend/src/components/LeftMenu/LeftMenu.css
> +  .search-item {
In develop branch it has search-item class

2024-10-04 12:29 UTC, erenfn requested changes
It is good to go after you delete 

- [ ] .search-item in LeftMenu.css line 30 
- [ ] Delete .DS_Strore

2024-10-06 13:28 UTC, erenfn approved these changes

2024-10-06 13:28 UTC, erenfn approved these changes

2024-10-06 17:44 UTC, merged