Add Loader while Auth Token is verified
bluewave-labs/bluewave-onboarding pull request #267
Opened 2024-10-05 17:07 UTC by mr-loop-1

fixes #247 

Added a loading page and isFetching state

2024-10-05 17:13 UTC, mr-loop-1 commented
@erenfn 
I added a very simple loader for now.
![image](https://github.com/user-attachments/assets/4f028c00-a3b1-4fc1-b15a-56395afd85e1)

2024-10-06 13:10 UTC, erenfn requested changes
- Put the loader on the center of the screen.
- Also the left menu should stay there. Only the contents part should change and that's where the loader should be.

@gorkem-bwl Also maybe we can remove the square pattern in the background

Thank you

2024-10-06 18:16 UTC, mr-loop-1 commented
@erenfn can you tell why these routes are enclosed with `Private`. Also, this Private component again has the same auth check which is performed already. I think we can remove it.
https://github.com/bluewave-labs/bluewave-onboarding/blob/065d4ccdf6971d94bb219965c64ef83b0e8a0370/frontend/src/App.jsx#L36-L38

2024-10-06 18:26 UTC, erenfn commented
Private ensures that at every page navigation the user is logged in. This check is for frontend. AuthenticateJWT is for backend

2024-10-06 19:09 UTC, mr-loop-1 commented
@erenfn I think it would be difficult to retain the sidebar while doing refresh. The reason being `LeftMenu` imports `UserProfileSidebar` which in turn uses 
https://github.com/bluewave-labs/bluewave-onboarding/blob/065d4ccdf6971d94bb219965c64ef83b0e8a0370/frontend/src/components/UserProfileSidebar/UserProfileSidebar.jsx#L13

This makes it circular, we want to show reload page till userInfo is populated (or logout), but also want to use this userInfo on reload page.

2024-10-06 19:15 UTC, mr-loop-1 commented on frontend/src/App.jsx
> -        <Route path="/" element={isLoggedIn ? <Private Component={HomePageTemplate} /> : <LoginPage />}>
Actually I was pointing here, that Private is already wrapped on top, so we don't require on individual routes below.

2024-10-07 09:19 UTC, erenfn commented on frontend/src/App.jsx
> -        <Route path="/" element={isLoggedIn ? <Private Component={HomePageTemplate} /> : <LoginPage />}>
I see what you mean. But think of this scenario: the user types {{url}}/banner into the browser without logging in. Since isLoggedIn is false, the LoginPage is rendered first, and the check in the Private component isn’t executed. This might not be the most efficient solution, so if you have any suggestions, please mention them. However, simply removing Private from these components will not work.

2024-10-07 09:23 UTC, erenfn commented
> @erenfn I think it would be difficult to retain the sidebar while doing refresh. The reason being `LeftMenu` imports `UserProfileSidebar` which in turn uses
> 
> https://github.com/bluewave-labs/bluewave-onboarding/blob/065d4ccdf6971d94bb219965c64ef83b0e8a0370/frontend/src/components/UserProfileSidebar/UserProfileSidebar.jsx#L13
> 
> This makes it circular, we want to show reload page till isLoggedIn (along with userInfo is set), but also want to use this userInfo on reload page.

You can try to call the useAuth in the parent component and pass down the props or a better solution might be to move userInfo to redux.

2024-10-07 09:49 UTC, mr-loop-1 commented
@erenfn the problem is LoadingPage itself exists beacuse useAuth is not resolved at that time.
When LoadingPgae renders, useAuth is still running.

2024-10-07 11:23 UTC, erenfn commented
Then maybe we can cache the userInfo data or using local stotage as starting value and updating it when useAuth returns.

2024-10-07 16:23 UTC, mr-loop-1 commented
@erenfn now it works

2024-10-08 14:13 UTC, erenfn commented
Good to merge after you remove the square background and center the loader 

![image](https://github.com/user-attachments/assets/41f690a1-41f1-464a-9442-4df04835587f)

2024-10-09 11:18 UTC, mr-loop-1 commented
@erenfn done

2024-10-09 17:23 UTC, erenfn approved these changes

2024-10-09 17:24 UTC, merged