Refactor popup button actions to an enum #291
bluewave-labs/bluewave-onboarding pull request #300
Opened 2024-10-16 23:29 UTC by NohaFahmi

This PR includes the refactoring button actions to an enum.

- [x] added 2 enums one for types corresponding to numbers (actions types) and one for types corresponds to names (actions names)
- [x] add actions options list to constants
- [x] handle using enums in popup components and update handle button Action functionality
- [x] handle sending the selected action type enum value not name to create/edit payload for APIs
- [x] handle using the same enum in backend 
- [ ] apply same on banners and hints (waiting for confirmation on what's done on popups)

2024-10-16 23:36 UTC, NohaFahmi commented
Note: I couldn't test the changes I done on backend cause I had an issue running the DB, I run the docker successfully and APIs locally working fine in postman but it return 500 due to DB error.
I get this error when run the backend project and I couldn't figure a way to fix it

![image](https://github.com/user-attachments/assets/75fbea8e-7107-44d9-b556-17043cb706ea)

2024-10-17 01:16 UTC, erenfn commented
> Note: I couldn't test the changes I done on backend cause I had an issue running the DB, I run the docker successfully and APIs locally working fine in postman but it return 500 due to DB error. I get this error when run the backend project and I couldn't figure a way to fix it
> 
> ![image](https://private-user-images.githubusercontent.com/33437197/377261484-75fbea8e-7107-44d9-b556-17043cb706ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMjc4NTYsIm5iZiI6MTcyOTEyNzU1NiwicGF0aCI6Ii8zMzQzNzE5Ny8zNzcyNjE0ODQtNzVmYmVhOGUtNzEwNy00NGQ5LWI1NTYtMTcwNDNjYjcwNmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDAxMTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiODlkYmZkYjZjYzJmYzRjNzQwMTcwYThiM2M2ZDJjMjlmYWE3YmQ4YTZjMTQxMTFjM2FlYzhmYzAwMmViZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UMADL20oTaGH5wA7A9zDgueASpGmY7TyD6nVr-vdsLQ)

Use docker: `docker compose up` or change host in backend/config/config from db to localhost

2024-10-17 01:21 UTC, erenfn commented
Also take a look at coderabbit's suggestions; some actually look useful

2024-10-17 18:01 UTC, erenfn requested changes
- [ ] Can you also modify the frontend and backend for the Banner and Hint? They are pretty similar. (You can do this in a separate PR if you prefer.)

- [ ] Additionally, can you add a functionality to the backend where, if the buttonAction is a string, it is converted into an integer using the enum?

2024-10-18 09:32 UTC, uparkalau commented on frontend/src/utils/constants.js
> +export const ACTIONS_Names = Object.freeze({
All constant name has to be CAPITAL

2024-10-18 09:33 UTC, uparkalau commented on backend/src/models/Popup.js
> +        type: DataTypes.INTEGER,
Since you are making changes in the database you have to create a migration for that

2024-10-18 18:29 UTC, NohaFahmi commented
Hi @erenfn , @uparkalau, 
I did the changes you've requested but I am getting an error regarding importing from constants.json inside shared floder in root, here it is, it happens even if I used relative path to shared in import statement and  I can't resolve it, any advice?
![image](https://github.com/user-attachments/assets/8902a8e8-1a1b-43e7-89e2-24a47b23a66a)

2024-10-18 21:37 UTC, erenfn commented
I'll have to look into that, but my guess is 'npm run dev' only uses the files under that folder (I may be wrong). Since shared it outside that folder, it may not exist in the server files. If it is that case, me may either have to change the scope or move the enums back to the folders. For this instance,  I'll prefer the second one.

2024-10-19 11:46 UTC, NohaFahmi commented
> I'll have to look into that, but my guess is 'npm run dev' only uses the files under that folder (I may be wrong). Since shared it outside that folder, it may not exist in the server files. If it is that case, me may either have to change the scope or move the enums back to the folders. For this instance, I'll prefer the second one.

so do I go for the second option and move the enums back to folders as you suggested?

2024-10-20 13:52 UTC, erenfn commented
> I'll have to look into that, but my guess is 'npm run dev' only uses the files under that folder (I may be wrong). Since shared it outside that folder, it may not exist in the server files. If it is that case, me may either have to change the scope or move the enums back to the folders. For this instance, I'll prefer the second one.

It turns out this wasn't the issue because I was able to run both the frontend and backend servers locally. The errors only occur in Docker. If you broaden the scope to include the shared folder, I think it will solve the issue.

2024-10-26 02:23 UTC, erenfn commented
How is this issue going?

2024-10-30 14:44 UTC, closed without merging