Create hint design
bluewave-labs/bluewave-onboarding pull request #306
Opened 2024-10-19 04:02 UTC by thomastepi

- Replaced the static preview with previewComponent prop.
- created hint preview component.

2024-10-20 14:08 UTC, erenfn requested changes
This breaks the current implementation of the Popup Preview Component. Make the necessary changes so that both the Popup and Hint components work, and ensure it accommodates future components like Tours (although the design is not yet finished).

2024-11-02 15:12 UTC, gorkem-bwl commented
Hi @thomastepi - any updates here?

2024-11-03 09:16 UTC, thomastepi commented
> Hi @thomastepi - any updates here? 
in progress. will push today @gorkemcetin

2024-11-06 11:46 UTC, erenfn commented on frontend/src/scenes/login/Login.module.css
> +  /* padding: 8px 12px; */
why did you comment this out?

2024-11-06 11:52 UTC, erenfn requested changes
Selecting popup size as large causes overflows.

![image](https://github.com/user-attachments/assets/6e890d82-9d40-426d-8137-2bd6107b4b5e)

Also we can get rid of the grey part at the bottom in the popup

![Ekran görüntüsü 2024-11-06 144832](https://github.com/user-attachments/assets/7e4c8097-c5e1-4cd8-9dc5-310b24cad3cf)

2024-11-07 02:38 UTC, uparkalau requested changes
Review Coderabbit recommendation. Resolve that suggestions what make sense.

2024-11-07 14:44 UTC, gorkem-bwl commented
> Fixed overflow and removed the grey area at the bottom. For large popup sizes, should the dialog maintain a fixed width with horizontal scroll or expand/shrink based on content width? @erenfn

Let's expand/shrink the popup based on the content width.

2024-11-11 15:47 UTC, erenfn requested changes
- In hint preview, these buttons on the bottom are over each other
![image](https://github.com/user-attachments/assets/bcab7e26-d54e-4704-b01b-259d1e04c969)
- In create new popup content, I think the 'Editor' and 'preview' buttons are not used to calculate the modal size. That's why they don't fit the screen adn we get the grey area at the bottom
![image](https://github.com/user-attachments/assets/8ed65bac-a820-4dd9-b204-d0c666b3e1f2)
- Also after creating/editing a popup/hint the default page doesn't fetch the new popup/hint automatically to show it on the screen
![image](https://github.com/user-attachments/assets/59316125-5c37-4ff4-af79-09f23ffdd538)

2024-11-11 15:50 UTC, erenfn commented
I previously set the position of the 'Editor' and 'Preview' buttons to absolute. This was because, when you change the size of the popup or hint, I wanted those buttons to stay in place and not get pushed. You can change it if you want. Or @gorkem-bwl should be move them to the top of the right section instead of the bottom?

2024-11-11 16:10 UTC, erenfn commented on frontend/src/products/Hint/HintComponent.jsx
> +        />
What do you think about this suggestion?

2024-11-13 01:52 UTC, gorkem-bwl commented
> I previously set the position of the 'Editor' and 'Preview' buttons to absolute. This was because, when you change the size of the popup or hint, I wanted those buttons to stay in place and not get pushed. You can change it if you want. Or @gorkem-bwl should be move them to the top of the right section instead of the bottom?

I think it's good as is. When the size of the popup changes they should stay in place.

2024-11-13 12:08 UTC, erenfn commented
Then maybe we can add a `maxHeight` (of the preview component) prop to `RichTextEditor` to calculate where we should place the editor and preview buttons

2024-11-16 16:13 UTC, erenfn requested changes
Looks good! After you change the `CreateBanner` route like popup, and resolve the conflicts I think it is ready to merge. 

Also @gorkem-bwl Should we set the minimum height of the popup to the maximum height of the content and appearance sections? Switching between the two could cause the popup height to change, which might be eye-straining.

![image](https://github.com/user-attachments/assets/2ac5fa9e-1562-4025-abb8-1970712bc3c2)

![Ekran görüntüsü 2024-11-16 191001](https://github.com/user-attachments/assets/2fb81e9f-6c84-4206-8e4b-a01e2994c655)

2024-11-16 19:01 UTC, gorkem-bwl commented
> Also @gorkem-bwl Should we set the minimum height of the popup to the maximum height of the content and appearance sections? Switching between the two could cause the popup height to change, which might be eye-straining.

Yep, that makes sense. Overall the design looks good otherwise.

2024-11-16 19:01 UTC, gorkem-bwl requested changes
Minor changes requested.

2024-12-18 21:20 UTC, erenfn commented
Created #401 with the merged changes

2024-12-18 21:20 UTC, closed without merging