Settings Integration
bluewave-labs/bluewave-onboarding pull request #308
Opened 2024-10-19 19:38 UTC by mr-loop-1

DRAFT

2024-10-19 19:54 UTC, mr-loop-1 commented on frontend/src/scenes/settings/TeamTab/TeamTable/TeamTable.jsx
> +                {member.role}
@erenfn @uparkalau could you please add the drop-down for selecting new user role here. It is getting difficult for me to style the drop down according to the designs and also the event handling in material ui.

2024-10-20 14:03 UTC, erenfn commented on frontend/src/scenes/settings/TeamTab/TeamTable/TeamTable.jsx
> +                {member.role}
Sure, on it

2024-10-20 14:12 UTC, erenfn commented on frontend/src/scenes/settings/TeamTab/TeamTable/TeamTable.jsx
> +                {member.role}
Are you talking about this Dropdown list?

![image](https://github.com/user-attachments/assets/899d8a76-c401-421d-87ed-aaee0414085d)

2024-10-20 14:15 UTC, mr-loop-1 commented on frontend/src/scenes/settings/TeamTab/TeamTable/TeamTable.jsx
> +                {member.role}
This one to change role.
![Screenshot_20241020_194418_Chrome.jpg](https://github.com/user-attachments/assets/4a346a28-7fe1-4f14-9fe6-03ef3f242345)

2024-10-20 14:18 UTC, mr-loop-1 commented on frontend/src/scenes/settings/TeamTab/TeamTable/TeamTable.jsx
> +                {member.role}
Basically, we dont need to select the role hand to hand. Instead I need to call a setter fn that pushes a confirmation modal on the screen.

So, I need the list items to be like buttons instead of selectable items.

You can commit the changes in this pr. I only need the frontend as fn are aleeady there.

2024-10-20 16:14 UTC, erenfn commented on frontend/src/scenes/settings/TeamTab/TeamTable/TeamTable.jsx
> +                {member.role}
Pushed the changes

2024-10-22 13:23 UTC, mr-loop-1 commented on frontend/src/components/Modals/ChangeMemberRoleModal/ChangeMemberRoleModal.jsx
> +};
Can't do it because initially selectedMember is null

2024-10-22 13:45 UTC, mr-loop-1 commented on backend/src/controllers/team.controller.js
> +  const { memberId } = req.params;
done in middleware

2024-10-22 13:46 UTC, mr-loop-1 commented on backend/src/controllers/team.controller.js
> +    await teamService.updateUserRole(memberId, role);
done in middleware

2024-10-22 13:46 UTC, mr-loop-1 commented on backend/src/controllers/team.controller.js
> +      await teamService.updateTeam(name);
done in middleware

2024-10-22 14:30 UTC, mr-loop-1 commented on frontend/src/scenes/settings/TeamTab/TeamTable/TeamTable.jsx
> +                    menuItems={roles.filter(role=>role!=member.role).map(role => ({ text: role, onClick: handleChangeRole }))}
already done

2024-10-22 14:55 UTC, mr-loop-1 commented on frontend/src/scenes/settings/TeamTab/TeamTab.jsx
> +  }
done through input element

2024-10-22 14:56 UTC, mr-loop-1 commented on frontend/src/scenes/settings/TeamTab/TeamTab.jsx
> +  }
done through modal

2024-10-22 14:56 UTC, mr-loop-1 commented on frontend/src/scenes/settings/TeamTab/TeamTab.jsx
> +              <TabPanel sx={{ padding: 0, marginTop: '1.2rem' }} value="3"><TeamTable team={team.filter((user) => user.role=="member")} setRemoveModalOpen={setOpenRemoveTeamMemberModal} setChangeRole
optional

2024-10-22 17:38 UTC, erenfn requested changes
![image](https://github.com/user-attachments/assets/34ffd5d3-662f-42b4-b746-235f396d016a)

full name  in UserProfileSidebar (bottom left) is not updated without a refresh. I think another contributor created updateProfile in authProvider for this issue

2024-10-23 03:49 UTC, mr-loop-1 commented on backend/src/controllers/user.controller.js
> +    return res.status(200).json({ message: "User updated successfully", user: {id: user.id, name: user.name, surname: user.surname, email: user.email, role: settings.user.roleName[user.role]} });
outdated

2024-10-23 03:59 UTC, mr-loop-1 commented
@erenfn it is already fixed in develop, merged here now.

2024-10-25 13:40 UTC, mr-loop-1 commented
The name of route was changed here in develop i.e. why it didn't work
https://github.com/bluewave-labs/bluewave-onboarding/blob/e55a027bfe9c037d53797da8b0afc750e8247819/backend/src/routes/user.routes.js#L17

I was fixing it and noticed that the team tab is throwing error of Content-Length missing (which shouldn't be for GET)
I think that this middleware is being run for all requests
https://github.com/bluewave-labs/bluewave-onboarding/blob/e55a027bfe9c037d53797da8b0afc750e8247819/backend/index.js#L29

2024-10-25 14:13 UTC, erenfn commented
Yes, that middleware doesn't work. You can comment it out

2024-10-25 14:53 UTC, mr-loop-1 commented
@erenfn did the changes

2024-10-26 02:02 UTC, erenfn submitted a review, later dismissed

2024-10-26 02:05 UTC, erenfn commented
Now it works. The only issue is after you update the profile picture, the popup still remains:

![image](https://github.com/user-attachments/assets/5e27992b-647e-46c7-992e-b17b96f4b705)

And after you upload the image, it isn't saved in the database (the changes disappear after you refresh). However, I think this is beyond the scope of this PR. Once you resolve the conflicts, it will be ready to merge. I'll create a new issue for this.

2024-10-26 02:09 UTC, erenfn commented
Maybe it is related to #235 We'll deal with that in a later PR

2024-10-26 18:32 UTC, erenfn approved these changes

2024-10-26 18:32 UTC, merged