Create migrations for tour, hints, banners and popup_logs table
bluewave-labs/bluewave-onboarding pull request #312
Opened 2024-10-22 19:23 UTC by jaykayudo

Resolves https://github.com/bluewave-labs/bluewave-onboarding/issues/309

2024-10-22 19:41 UTC, jaykayudo commented on backend/migrations/20241022170915-create-popup_logs-table.js
> +    });
The models specified no timestamps

2024-10-22 20:55 UTC, erenfn commented
Are the migrations any different from the models? The question is, will we encounter different behavior when running migrations versus using `sequelize.sync()`

2024-10-22 21:27 UTC, erenfn commented on backend/migrations/20241022153237-create-banners-table.js
> +        allowNull: true,
For example, in the original modal did we have this?

2024-10-23 20:20 UTC, jaykayudo commented
@erenfn  does this PR meet the requirements of the task?

2024-10-25 12:10 UTC, erenfn commented
Yes, but do not add checks that are not in the models.

2024-10-25 12:10 UTC, erenfn commented on backend/migrations/20241022153237-create-banners-table.js
> +        validate: {
For example, delete this isUrl validation

2024-10-25 12:14 UTC, erenfn commented on backend/migrations/20241022153237-create-banners-table.js
> +      },
This can be implemented on both the model and in the migration

2024-10-25 12:16 UTC, erenfn commented
You also have to include other vallidations. For example:

```
        validate: {
          isValidAction(value) {
              validateActionButton(value);
          },
        },
```

These should be in the migrations

2024-10-25 21:42 UTC, jaykayudo commented
> You also have to include other vallidations. For example:
> 
> ```
>         validate: {
>           isValidAction(value) {
>               validateActionButton(value);
>           },
>         },
> ```
> 
> These should be in the migrations

@erenfn  Done

2024-10-26 02:07 UTC, erenfn commented on backend/migrations/20241022190720-create-tours-table.js
> +      },
Can you look at this comment? @jaykayudo

2024-10-26 22:05 UTC, erenfn approved these changes

2024-10-26 22:08 UTC, erenfn requested changes

2024-10-26 22:08 UTC, erenfn commented on backend/migrations/20241022153237-create-banners-table.js
> -        type: Sequelize.ENUM("no action", "open url", "open url in a new tab"),
Can you also revert Sequelize.string to these enums like you did in the past?

2024-10-26 22:47 UTC, erenfn requested changes

2024-10-26 22:47 UTC, erenfn commented on backend/migrations/20241022153237-create-banners-table.js
> +    await queryInterface.addIndex('banners', ['created_by']);
I get this error. It is probably because of a typo here:

ERROR: column "created_by" does not exist

Please test the migrations using 
`
npx sequelize-cli db:migrate`

2024-10-26 23:40 UTC, erenfn commented
Did you push the changes? you just have to change created-by to createdBy

2024-10-26 23:57 UTC, jaykayudo commented
> Did you push the changes? you just have to change created-by to createdBy

Sorry about that. I mistakely removed it while i was testing.

2024-10-27 01:14 UTC, erenfn approved these changes

2024-10-27 01:14 UTC, merged