PR for Issue#303
bluewave-labs/bluewave-onboarding pull request #327
Opened 2024-10-27 09:13 UTC by d02ev

1. Created backend endpoint to set an organization with appropriate validations.
2. First time registering users are routed to the progress steps page instead of home page directly.
3. Invites and organization name setting are done on the last step of the progress step page.

2024-10-27 15:32 UTC, erenfn requested changes

2024-10-27 15:32 UTC, erenfn commented on backend/src/controllers/team.controller.js
> +    const orgExists = await teamService.getTeamByName(name);
You don't need to check team by name. Just check if there is a team team or not. There will be just one team and and that team will be set when the first user (the admin) logs in. 

Also I think currently we add a team, when we start the project in backend/index.js. You can remove it. 

Ultimately, when the server starts running, initially there will be no teams. And when the first user logs in and calls this endpoint it will create the team. But we add the check I mentioned above to not allow anymore teams to be created

2024-10-27 15:35 UTC, d02ev commented on backend/src/controllers/team.controller.js
> +    const orgExists = await teamService.getTeamByName(name);
Okay, so rather than checking if a name exists. I need to check if the `teams` table is empty or not. If it is empty, an organisation is created else it is not created.

2024-10-27 15:38 UTC, erenfn commented on backend/src/controllers/team.controller.js
> +    const orgExists = await teamService.getTeamByName(name);
Yes. Also please check coderabbit's suggestions. Some might be useful

2024-10-27 15:39 UTC, d02ev commented on backend/src/controllers/team.controller.js
> +    const orgExists = await teamService.getTeamByName(name);
Sure will do.

2024-10-28 11:49 UTC, erenfn requested changes
![image](https://github.com/user-attachments/assets/6467ef70-e168-43c2-8d14-2d580cd05870)

- After an invalid email the 'Sweet' button is disabled, and when I change the email to a valid email it stays disabled - I had to refresh the page. 

- [ ] Do the necessary checks before we arrive at the final page.

![Ekran görüntüsü 2024-10-28 143604](https://github.com/user-attachments/assets/4621aefd-b402-4c95-a128-89919f20d968)

- When I enter an empty organization name I just gives this generic error. Change the error message to indicate that the org name is empty, and check it before we arrive at the final page

@gorkem-bwl Please provide your feedback, if any, regarding the display of error messages.

2024-10-28 11:49 UTC, erenfn commented on backend/index.js
> +//   .sync({ force: true })
Just remove the table creation part. You can keep

```
sequelize
  .sync({ force: true })
  .then(() => console.log("Models synced with the database..."))
  .catch((err) => console.log("Error syncing models: " + err));
```

2024-10-28 11:53 UTC, erenfn commented on frontend/src/utils/loginHelper.js
> +    if (authType === AUTH_TYPE.SIGNUP) {
Additionally, we should navigate to the progress steps only once, not with every sign-up. You can add a check before navigating, such as verifying if a team has already been created.

2024-10-28 12:19 UTC, d02ev commented on frontend/src/utils/loginHelper.js
> +    if (authType === AUTH_TYPE.SIGNUP) {
So with the same previous logic of creating the team, If the teams tables has values. Navigate to home page after signup

2024-10-29 06:55 UTC, d02ev commented on frontend/src/utils/loginHelper.js
> +    if (authType === AUTH_TYPE.SIGNUP) {
Also, should I create a check for the first step so that when the check box is click the input is enabled else disabled?

2024-10-29 12:46 UTC, erenfn commented on frontend/src/utils/loginHelper.js
> +    if (authType === AUTH_TYPE.SIGNUP) {
Actually, we can just remove that checkbox. I don't see any good use for it

2024-10-30 12:47 UTC, erenfn commented
I think you may not have pushed your changes. Also, please check if the 'invite' section allows inviting multiple emails. An email should be added to the list when the user presses Enter in that field.

![image](https://github.com/user-attachments/assets/60a0eea6-00c4-4413-9015-3e6cd9ed1f61)

2024-10-30 12:50 UTC, d02ev commented
Yes, I have not yet pushed the latest changes. I wanted to get your views before pushing any further updates. Also, the invite section allows for multiple emails, that functionality remains untouched. I will push these latest changes now.

2024-10-30 13:04 UTC, erenfn requested changes
When you start typing an email but then delete it, the Next button remains disabled. I suggest activating the email check when the user presses Enter and keeping the Next button enabled at all times.

![image](https://github.com/user-attachments/assets/840265be-4560-4c66-ac12-e232ebf2704e)

2024-10-30 13:16 UTC, erenfn commented on backend/src/routes/team.routes.js
> +router.get("/count", authenticateJWT, getTeamCount);
"The /count endpoint might expose sensitive team information."

Also, this is true. You can change this endpoint by just returning a boolean value.

2024-10-30 13:53 UTC, gorkem-bwl commented
Also make sure you add 8px between inputs here.

Also, did you copied those inputs from our components folder?

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/59fbe95c-ea30-4da8-ad19-c3ba7c15182b">

2024-10-30 14:28 UTC, d02ev commented
I made changes to the `ProgressStepsMain` component itself. I did not copy any components.

2024-10-30 15:48 UTC, d02ev commented
> When you start typing an email but then delete it, the Next button remains disabled. I suggest activating the email check when the user presses Enter and keeping the Next button enabled at all times.
> 
> ![image](https://private-user-images.githubusercontent.com/81182796/381558871-840265be-4560-4c66-ac12-e232ebf2704e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTkwNDEsIm5iZiI6MTczMDI5ODc0MSwicGF0aCI6Ii84MTE4Mjc5Ni8zODE1NTg4NzEtODQwMjY1YmUtNDU2MC00YzY2LWFjMTItZTIzMmViZjI3MDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE0MzIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNWExODQ1NWRjMmU1ZTBmNWZiMTU5MTZkNjJjNzA4ZjEzOGM4OGNmYWM5NTJkYjUxNmEwNTQ0NTI2OTkwZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.COyWfFl7_oMgI-TcCvbyEdHI0DM5y0KsdOLeVb7G1uU)

Here's a screen recording, where only when the user presses `Enter` the email validations are done and also these invalid emails are not added to the list and when the user enters a valid email and presses `Enter`, the error message disappears and the email is added to the list. I have also removed button being disabled if the validation fails, should I make this field required ? or keep it as it is
[Screencast from 2024-10-30 21-15-13.webm](https://github.com/user-attachments/assets/e90ba7e9-6364-4155-9542-a2b96a45eeef)

2024-10-30 16:08 UTC, d02ev commented
> You can make the field for organization name required. The validation for email invites looks good now

If an error occurred either while setting an organization or sending invites in the last step. Should I display a generic error or an error toast and navigate the user to home page ?

2024-10-30 16:14 UTC, erenfn commented
Don’t navigate the user to the home page if an error occurs. Instead, display the error message on the last step to prompt the user to make changes. Ideally, though, we shouldn't encounter an error in the last step, as the necessary checks are done beforehand.

2024-10-30 20:40 UTC, erenfn approved these changes

2024-10-30 20:48 UTC, merged