331 fe code snippet
bluewave-labs/bluewave-onboarding pull request #340
Opened 2024-11-05 19:51 UTC by erenfn

Solves #331 
![image](https://github.com/user-attachments/assets/e9d228ad-0db8-4679-8127-9810c9f329e9)

2024-11-07 02:22 UTC, uparkalau commented on backend/src/service/team.service.js
> +            }, {
Do you want to resolove it? @erenfn

2024-11-07 02:23 UTC, uparkalau commented on backend/src/service/team.service.js
>      }
Since we were using transactions it make sense to implement it here .

2024-11-07 02:25 UTC, uparkalau requested changes
Review Code rabbit recommendation and implement what is make sense.

2024-11-08 01:34 UTC, erenfn commented
> Review Code rabbit recommendation and implement what is make sense.

@uparkalau done

2024-11-11 02:27 UTC, uparkalau approved these changes

2024-11-11 14:28 UTC, merged