302 implement create helper link page
bluewave-labs/bluewave-onboarding pull request #342
Opened 2024-11-07 22:18 UTC by DeboraSerra

2024-11-08 01:01 UTC, erenfn requested changes
When I run in docker I cannot add a new link

![image](https://github.com/user-attachments/assets/b6a21909-f020-464f-83a5-9c0684b21ee5)

2024-11-08 16:58 UTC, erenfn commented on frontend/src/components/Links/Preview/index.jsx
> +import { default as CloseRoundedIcon } from "@mui/icons-material/CloseRounded";
Also can we move Preview under /products as HelperLinkComponent.jsx? These components are also going be used in our scripts

2024-11-08 23:22 UTC, DeboraSerra commented on frontend/src/components/Links/Preview/index.jsx
> +import { default as CloseRoundedIcon } from "@mui/icons-material/CloseRounded";
The first point was the because the helper link didn't have a title... I fixed it by improvving the error handling.
The second point, I don't know if using the transactions made if work or not, but on my side it is working properly. If you could test it again.
Third and fourth points done.

2024-11-08 23:44 UTC, erenfn requested changes
- I get this error: `An error occurred: Invalid value for title or url` with values` title:title` `url:/url` I think this shouldn't happen.
- Also I get `An error occurred: title is required` when the header is missing, not the title. This error message can be misleading. It would be good if you can change it
- Can you create migrations for the newly created tables? 
- Additionally, it would be great if text insertion into the title field could start automatically when 'Add a New Link' is clicked, without requiring the user to click on the title textbox. This feature is optional but would be a nice enhancement.

2024-11-08 23:46 UTC, erenfn commented on frontend/src/components/Links/Settings/Settings.jsx
> -  const handleClickOutside = (e) => {
You don't have to delete this; I think it’s a good feature. What I was trying to say earlier is to check that both 'clicking' and 'releasing' occur outside the popup, not just 'releasing' alone.

2024-11-08 23:47 UTC, erenfn commented
Also take a look at codeRabbit's suggestions. Some might be useful

2024-11-09 00:12 UTC, DeboraSerra commented on frontend/src/components/Links/Settings/Settings.jsx
> -  const handleClickOutside = (e) => {
I don't think I understand what you mean by clicking and releasing then...

2024-11-09 00:22 UTC, erenfn commented on frontend/src/components/Links/Settings/Settings.jsx
> -  const handleClickOutside = (e) => {
So, let's say a mouse click is pressing down the button + releasing the button. I am saying that the 'press down' should also start outside the popup to close it. We shouldn't close the popup it the user pressed down on the popup but released outside.

2024-11-09 00:23 UTC, erenfn commented on frontend/src/components/Links/Settings/Settings.jsx
> -  const handleClickOutside = (e) => {
Try the example I mentioned in my previous review. That may help

2024-11-09 00:54 UTC, DeboraSerra commented on frontend/src/components/Links/Settings/Settings.jsx
> -  const handleClickOutside = (e) => {
Got it...
Will work on it

2024-11-09 01:10 UTC, DeboraSerra commented on frontend/src/components/Links/Settings/Settings.jsx
> -  const handleClickOutside = (e) => {
I think it's done.
I'll move to coderabbit suggestions, now

2024-11-11 15:10 UTC, erenfn commented
@coderabbitai resolve

2024-11-11 15:22 UTC, erenfn commented
@coderabbitai resolve

2024-11-11 15:34 UTC, erenfn requested changes
All other issues are perfectly resolved. After you make these minor improvements and merge develop into your branch it is ready to merge

2024-11-11 15:34 UTC, erenfn commented on frontend/src/services/linkService.js
> +};
this may be implemented

2024-11-11 15:34 UTC, erenfn commented on frontend/src/services/linkService.js
> +};
We can also add this. Let's say the url in a helper link is '/link' if we remove ''/' and then save it we get this in the console and we don't get a toast notification.

![image](https://github.com/user-attachments/assets/a3da2797-63b2-4966-8e4d-d9f6b60a983c)

2024-11-12 01:06 UTC, DeboraSerra reviewed
All the changes where applyed and made a pull from develop branch.

2024-11-12 12:48 UTC, erenfn requested changes
For some reason, now I am getting this error in backend while trying to add a link without a header. We didn't have this before

```

db-1                  | 2024-11-12 12:46:22.161 UTC [44] STATEMENT:  SELECT "Link"."id", "Link"."title", "Link"."url", "Link"."order", "Link"."target", "Link"."helperId", "helper"."id" AS "helper.id", "helper"."title" AS "helper.title", "helper"."headerBackgroundColor" AS "helper.headerBackgroundColor", "helper"."linkFontColor" AS "helper.linkFontColor", "helper"."iconColor" AS "helper.iconColor", "helper"."createdBy" AS "helper.createdBy" FROM "link" AS "Link" LEFT OUTER JOIN "helper_link" AS "helper" ON "Link"."helperId" = "helper"."id" WHERE "Link"."id" = '1245737648730';
db-1                  | 2024-11-12 12:46:22.961 UTC [44] ERROR:  value "1245737648730" is out of range for type integer at character 497
```

The toast message on the frontend is `An error occurred. Please check your network connection and try again.`

2024-11-12 19:38 UTC, DeboraSerra commented
I changed the logic to display a toast with more meaningfull description.

2024-11-13 00:04 UTC, erenfn requested changes
- Is it possible to prevent the LinkContent section from reloading when adding or editing a link fails? The rerender is redundant.
- After new changes when trying to add a link the server crashed.

```
onboarding_backend-1  | /app/src/controllers/helperLink.controller.js:58
onboarding_backend-1  |         const response = result.filter((it) => it.msg);      
onboarding_backend-1  |                                                   ^          
onboarding_backend-1  | 
onboarding_backend-1  | TypeError: Cannot read properties of undefined (reading 'msg')                                                                                    
onboarding_backend-1  |     at /app/src/controllers/helperLink.controller.js:58:51
onboarding_backend-1  |     at Array.filter (<anonymous>)                            
onboarding_backend-1  |     at addHelper (/app/src/controllers/helperLink.controller.js:58:33)                                                                            
onboarding_backend-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)                                                                
onboarding_backend-1  | 
onboarding_backend-1  | Node.js v22.11.0         
```                                    
- Please ensure the code is tested thoroughly.

2024-11-13 01:46 UTC, DeboraSerra commented
Every test that I did is working...
I changed a little the controller to avoid this error, but all the situations I could think worked properly...
1: try to add link with url but no title
2: try to add link with title but no url
3: try to add helper without header
4: edit the helper and add a second link
5: change the links position and update the helper
6: create helper with common url and with relative url
7: change the target from the links and see if they are working

I think those were it... Did I miss any scenarion?

2024-11-13 13:14 UTC, erenfn requested changes
When trying to edit a link, clicking the save button the first time triggers an error. However, clicking it a second time successfully saves the changes. There might be an issue with fetching or sending the edit data.

![Ekran görüntüsü 2024-11-13 151452](https://github.com/user-attachments/assets/62b45942-d768-487d-b15d-0f9b8472840b)

2024-11-13 15:55 UTC, DeboraSerra commented
I was able to reproduce it now, and I believe I fixed it.
Tried again all the scenarios I mentioned before to make sure everything is still working

2024-11-13 23:08 UTC, erenfn requested changes
![image](https://github.com/user-attachments/assets/a7694da0-0225-409e-b42a-70a9418cf68a)

Can you check the url validation again? I was able to add an url without '/' or http

2024-11-13 23:38 UTC, erenfn approved these changes

2024-11-13 23:39 UTC, merged