PR for Issue#339
bluewave-labs/bluewave-onboarding pull request #343
Opened 2024-11-10 17:56 UTC by d02ev

1. Removed authentication for the `/count` BE endpoint.
2. Updated the UI for the registration form as suggested in the issue.
3. Added conditional routing to `/login` or `/signup` based upon the existence of teams or not respectively.

2024-11-10 18:04 UTC, d02ev commented
Since I have changed the UI of the `CreateAccountPage.jsx`, the build seems to fail in some old tests. @erenfn, let me know what needs to be changed in `CreateAccountPage.jsx` to fix the build issue.

2024-11-11 15:57 UTC, erenfn requested changes

2024-11-11 15:57 UTC, erenfn commented on frontend/src/components/Private.jsx
> +  useEffect(() => {
don't use useEffect. We should only call getTeamCount when isLoggedIn

2024-11-11 15:57 UTC, erenfn commented on frontend/src/scenes/login/CreateAccountPage.jsx
> +      <h2>Create admin account</h2>
I think you may have misunderstood the task. There are two `CreateAccountPage` files: one is the previous version, and the other is the one with the changes you made. We want to render the 'admin' create account page only when `getTeamCount `returns false. You can add a prop to `CreateAccountPage` like `isAdmin:=false` and use it to render these new changes conditionally.

2024-11-11 15:58 UTC, erenfn commented
Also when you make the changes don't forget to update the test files if a test fails

2024-11-11 17:06 UTC, d02ev commented on frontend/src/components/Private.jsx
> +  useEffect(() => {
Can you please elaborate more, I quite did not get what you said.

2024-11-11 17:10 UTC, d02ev commented on frontend/src/components/Private.jsx
> +  useEffect(() => {
Can you please elaborate more? I quite did not get it.

2024-11-11 20:30 UTC, d02ev commented on frontend/src/components/Private.jsx
> +  }, []);
@erenfn is this what you were referring to ?

2024-11-13 00:51 UTC, erenfn commented on frontend/src/components/Private.jsx
> +  }, []);
Yeah, kind of. `useEffect` will end up calling `fetchTeamCount `even when we are logged in and navigating through pages, which we don't want. We only want to call `fetchTeamCount` when the user is not logged in so that we can direct them to the Login or Create Account page.

2024-11-15 11:37 UTC, erenfn requested changes
Okay let's do it like this:

Revert all changes in `App.jsx` and `Private.jsx`. After I merge #346 I'll come back to this PR to do the second task: `Set the register page as the initial page when there are no users.`

2024-11-16 08:01 UTC, d02ev commented
> Okay let's do it like this:
> 
> Revert all changes in `App.jsx` and `Private.jsx`. After I merge #346 I'll come back to this PR to do the second task: `Set the register page as the initial page when there are no users.`

The changes regarding different sign up page based upon if an admin exists should also be removed ? or only regarding the routing to login or signup page ?

2024-11-16 12:42 UTC, erenfn commented
changes to sign up page can stay

2024-11-16 13:16 UTC, erenfn commented
The new changes might make the merging process quite messy. Thank you; you don’t need to do anything else. I can take it from here.

2024-11-16 13:16 UTC, closed without merging