Auth validations - Frontend and Backend
bluewave-labs/bluewave-onboarding pull request #346
Opened 2024-11-13 18:36 UTC by eulerbutcooler

- Used express-validator to validate the inputs on the backend.
- Used Formik and Yup for inform validations reducing the number of api calls made.
- All validations are checked onBlur event.

**Sign up**

- Added email format check, password length and special character check, name and surname no numeric values check.

**Sign in**

- Added email format check, password check.

**Forgot Password**

- Added email check.

2024-11-13 23:21 UTC, erenfn commented on backend/src/controllers/auth.controller.js
> +const findUserByEmail = async (email) => {
Can you move `findUserByEmail` to service?

2024-11-14 10:21 UTC, eulerbutcooler commented on backend/src/utils/auth.helper.js
> +];
@erenfn should i add spaces in the name and surname regex?

2024-11-14 10:22 UTC, eulerbutcooler commented on backend/src/controllers/auth.controller.js
> +const findUserByEmail = async (email) => {
just did it. pushing the code.

2024-11-14 10:46 UTC, eulerbutcooler commented on frontend/src/scenes/login/SetNewPassword.jsx
> +              )}
adding in the next commit

2024-11-14 10:48 UTC, eulerbutcooler commented on frontend/src/scenes/login/SetNewPassword.jsx
> +          }
adding in the next commit

2024-11-14 10:52 UTC, eulerbutcooler commented on frontend/src/scenes/login/ForgotPasswordPage.jsx
> +        setServerErrors([]);
it can be an array

2024-11-14 13:37 UTC, erenfn commented on backend/src/utils/auth.helper.js
> +];
Sure, we can add it

2024-11-14 13:46 UTC, erenfn requested changes
The code looks good, and the functionality is solid. The only remaining task is to modify some tests. After these changes, a few tests fail.

```
 ❯ src/tests/scenes/login/SetNewPassword.test.jsx:43:31

Error: TestingLibraryElementError: Unable to find an element with the text: Internal Server Error. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
```
```

 ❯ src/tests/scenes/login/LoginPage.test.jsx:43:33

Error: AssertionError: expected "spy" to be called with arguments: [ { email: 'asdf@asdf.com', …(1) } ]
```

etc.

You can run` npm run test` in the frontend directory to execute tests. Additionally, these tests will run on GitHub with every push.

2024-11-16 07:07 UTC, eulerbutcooler commented
@erenfn are these fine?

2024-11-16 12:54 UTC, erenfn commented
Maybe you didn't run `npm install` that's why. It passes all tests in Github now. Approving it.

2024-11-16 12:55 UTC, erenfn approved these changes

2024-11-16 13:10 UTC, merged