PR for Issue#332 [BE: API key & code snippet]
bluewave-labs/bluewave-onboarding pull request #347
Opened 2024-11-15 09:45 UTC by d02ev

**Note: ** This is the same PR #345, which I had to close due to some rebasing issues.

1. Created `serverUrl` and `apiKey` columns to the `teams` table.
2. Created `/set-config` BE route to store `serverUrl` and `apiKey`.
3. Added basic BE and FE request validations.
4. Connected the FE to the BE.

2024-11-15 09:53 UTC, d02ev commented on backend/migrations/20241115084356-api_key_server_url_cols_teams_rel.js
> +  },
@erenfn what do you suggest for encryption and decryption of `apiKey`.

2024-11-15 10:07 UTC, d02ev commented on backend/src/models/Team.js
> +        },
@erenfn what do you suggest for `apiKey` encryption before storing to db ?

2024-11-15 10:16 UTC, d02ev commented on backend/src/controllers/team.controller.js
> +  }
@erenfn give your view regarding `Rate limiting`

2024-11-15 11:30 UTC, erenfn commented on backend/src/models/Team.js
> +        },
Look at how we store the password in the db in `auth.controller` you can do the same for the api key

2024-11-15 11:31 UTC, erenfn commented on backend/src/controllers/team.controller.js
> +  }
We can do it later. It is not in the scope of this PR

2024-11-16 09:00 UTC, d02ev commented on backend/src/models/Team.js
> +        },
But If in future, we need to fetch the stored `apiKey` we will need to decrypt it and `bcrypt` library only supports hashing and comparison. I can make use of the `crypto` library for `encryption` and `decryption` but that would require an additional column in `teams` table `ivHex` which would be needed to decrypt the fetched encrypted `apiKey`.

2024-11-16 13:09 UTC, erenfn commented on backend/src/models/Team.js
> +        },
Can't we just store the decryption key in .env?

2024-11-16 16:36 UTC, d02ev commented on backend/src/models/Team.js
> +        },
> Can't we just store the decryption key in .env?

I used the `jsonwebtoken` instead to encrypt the `apiKey`. The `crypto` library was a bit complex.

2024-11-17 21:41 UTC, erenfn requested changes
The error message for the url is wrong. Here the url starts with https:// and the actual error message should be something like 'server url is not valid' since it is not in the form of X.Y

![image](https://github.com/user-attachments/assets/60e30005-64ef-4225-ac13-99d727316a65)

Also when you comeback you should see api key and server url in their fields.

2024-11-29 17:08 UTC, d02ev commented
> The error message for the url is wrong. Here the url starts with https:// and the actual error message should be something like 'server url is not valid' since it is not in the form of X.Y
> 
> ![image](https://private-user-images.githubusercontent.com/81182796/387007176-60e30005-64ef-4225-ac13-99d727316a65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MDAzNjAsIm5iZiI6MTczMjkwMDA2MCwicGF0aCI6Ii84MTE4Mjc5Ni8zODcwMDcxNzYtNjBlMzAwMDUtNjRlZi00MjI1LWFjMTMtOTlkNzI3MzE2YTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDE3MDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjN2ViZWU2NWQwOThjNGFlNzYzNzMxNDg2ZGI1ZWYwZjQwYjVkODgwOTM5NzNlYTdlODEwZGU0Y2FkOGFkY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s1xIgmQoG0R4AGw3OoHtYgR5b5BBpZ8cj2XITaUAxf4)
> 
> Also when you comeback you should see api key and server url in their fields.

fixed it in the latest commit

2024-12-02 01:07 UTC, erenfn requested changes
- `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'trim')`

I get this in the console when I try to save

![image](https://github.com/user-attachments/assets/5c723735-6db1-4a9a-ba6d-363e81694850)

I should be able to save that even though server url is empty.



- Provide a hint here that they should add https://, http:// etc. 

![image](https://github.com/user-attachments/assets/e01b62f3-dff8-48d8-96a0-163748f52e8e)

2024-12-02 01:07 UTC, erenfn commented on frontend/src/scenes/settings/CodeTab/CodeTab.jsx
> +            if (!['http:', 'https:'].includes(url.protocol)) {
It should be https:// http:// etc. Don't forget `//`

2024-12-02 16:03 UTC, d02ev commented
> * `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'trim')`
> 
> 
> I get this in the console when I try to save
> 
> ![image](https://private-user-images.githubusercontent.com/81182796/391378199-5c723735-6db1-4a9a-ba6d-363e81694850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTU0NDEsIm5iZiI6MTczMzE1NTE0MSwicGF0aCI6Ii84MTE4Mjc5Ni8zOTEzNzgxOTktNWM3MjM3MzUtNmRiMS00YTlhLWJhNmQtMzYzZTgxNjk0ODUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE1NTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2OTE2MzMwMWRkNmZkYmY4MzBhMzU0MmJjNTE3NjA5ZDVhNzZjYWZkYTc3M2QwN2UyMWUwNjhkYmIyODBiZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ecf9ERm9nl5bZiy20s840CEA-O19per27iaE9fwIwO8)
> 
> I should be able to save that even though server url is empty.
> 
>     * Provide a hint here that they should add https://, http:// etc.
> 
> 
> ![image](https://private-user-images.githubusercontent.com/81182796/391378618-e01b62f3-dff8-48d8-96a0-163748f52e8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTU0NDEsIm5iZiI6MTczMzE1NTE0MSwicGF0aCI6Ii84MTE4Mjc5Ni8zOTEzNzg2MTgtZTAxYjYyZjMtZGZmOC00OGQ4LTk2YTAtMTYzNzQ4ZjUyZThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE1NTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTc1MTU0MzFiZjZlOWU2OTQ4MzA4N2QwOWE5ZTBiNzU2MTI2Njk5ZTVhMmIyM2UxOWQ3OTQ4NjQ0Zjk1YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vAhnJVG7vCnIn4GEfyK0twue2jRzaK5lH6bTcBkh934)

Instead of triggering an error tooltip regarding the server URL, should I add realtime validations to it and disable the `Save` button till it is fixed ?

2024-12-02 16:08 UTC, d02ev commented on frontend/src/scenes/settings/CodeTab/CodeTab.jsx
> +            if (!['http:', 'https:'].includes(url.protocol)) {
The `url.protocol` property returns either `http:` or `https:`, it omits the `//`. If need be I can use a regex instead of this approach.

2024-12-02 19:17 UTC, erenfn commented
> > * `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'trim')`
> > 
> > I get this in the console when I try to save
> > ![image](https://private-user-images.githubusercontent.com/81182796/391378199-5c723735-6db1-4a9a-ba6d-363e81694850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTU0NDEsIm5iZiI6MTczMzE1NTE0MSwicGF0aCI6Ii84MTE4Mjc5Ni8zOTEzNzgxOTktNWM3MjM3MzUtNmRiMS00YTlhLWJhNmQtMzYzZTgxNjk0ODUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE1NTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2OTE2MzMwMWRkNmZkYmY4MzBhMzU0MmJjNTE3NjA5ZDVhNzZjYWZkYTc3M2QwN2UyMWUwNjhkYmIyODBiZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ecf9ERm9nl5bZiy20s840CEA-O19per27iaE9fwIwO8)
> > I should be able to save that even though server url is empty.
> > ```
> > * Provide a hint here that they should add https://, http:// etc.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/81182796/391378618-e01b62f3-dff8-48d8-96a0-163748f52e8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTU0NDEsIm5iZiI6MTczMzE1NTE0MSwicGF0aCI6Ii84MTE4Mjc5Ni8zOTEzNzg2MTgtZTAxYjYyZjMtZGZmOC00OGQ4LTk2YTAtMTYzNzQ4ZjUyZThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE1NTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTc1MTU0MzFiZjZlOWU2OTQ4MzA4N2QwOWE5ZTBiNzU2MTI2Njk5ZTVhMmIyM2UxOWQ3OTQ4NjQ0Zjk1YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vAhnJVG7vCnIn4GEfyK0twue2jRzaK5lH6bTcBkh934)
> 
> Instead of triggering an error tooltip regarding the server URL, should I add realtime validations to it and disable the `Save` button till it is fixed ?

yes that makes sense. But also allow empty string/null for server url. In case the user doesn't want to add a server url

2024-12-03 10:13 UTC, d02ev commented
> > > * `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'trim')`
> > > 
> > > I get this in the console when I try to save
> > > ![image](https://private-user-images.githubusercontent.com/81182796/391378199-5c723735-6db1-4a9a-ba6d-363e81694850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTU0NDEsIm5iZiI6MTczMzE1NTE0MSwicGF0aCI6Ii84MTE4Mjc5Ni8zOTEzNzgxOTktNWM3MjM3MzUtNmRiMS00YTlhLWJhNmQtMzYzZTgxNjk0ODUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE1NTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2OTE2MzMwMWRkNmZkYmY4MzBhMzU0MmJjNTE3NjA5ZDVhNzZjYWZkYTc3M2QwN2UyMWUwNjhkYmIyODBiZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ecf9ERm9nl5bZiy20s840CEA-O19per27iaE9fwIwO8)
> > > I should be able to save that even though server url is empty.
> > > ```
> > > * Provide a hint here that they should add https://, http:// etc.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ![image](https://private-user-images.githubusercontent.com/81182796/391378618-e01b62f3-dff8-48d8-96a0-163748f52e8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTU0NDEsIm5iZiI6MTczMzE1NTE0MSwicGF0aCI6Ii84MTE4Mjc5Ni8zOTEzNzg2MTgtZTAxYjYyZjMtZGZmOC00OGQ4LTk2YTAtMTYzNzQ4ZjUyZThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE1NTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTc1MTU0MzFiZjZlOWU2OTQ4MzA4N2QwOWE5ZTBiNzU2MTI2Njk5ZTVhMmIyM2UxOWQ3OTQ4NjQ0Zjk1YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vAhnJVG7vCnIn4GEfyK0twue2jRzaK5lH6bTcBkh934)
> > 
> > Instead of triggering an error tooltip regarding the server URL, should I add realtime validations to it and disable the `Save` button till it is fixed ?
> 
> yes that makes sense. But also allow empty string/null for server url. In case the user doesn't want to add a server url

Are there any more validations that need to be integrated for the `apiKey` and `serverUrl` ?

2024-12-03 14:59 UTC, erenfn commented
I don't think so

2024-12-03 18:23 UTC, d02ev commented
I am committing BE changes with validations suggested by you. Please take a look at it and let me know If the approach is correct or not, after which I will similar changes to the FE. Also the build is failing here but locally it is building without any error.

2024-12-04 14:05 UTC, erenfn commented on frontend/src/utils/constants.js
> +// export const API_BASE_URL = 'http://localhost:3000/api/';
please revert these

2024-12-04 23:06 UTC, erenfn commented
> I am committing BE changes with validations suggested by you. Please take a look at it and let me know If the approach is correct or not, after which I will similar changes to the FE. Also the build is failing here but locally it is building without any error.

It is related to some import in `PasswordTab`. You can ignore the build error

2024-12-07 15:01 UTC, d02ev commented
> It still doesn't allow null values to be saved to the database. For example, if the server URL is left blank but the API key is not, that is still a valid response, so we should save it to the database.

`null` values in the sense sending only the `apiKey` in the request body and not the `serverUrl` ?

2024-12-09 11:12 UTC, erenfn requested changes
`Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.`

Null values still don't work. I'll make the necessary changes by forking from your branch.

2024-12-09 11:31 UTC, d02ev commented
> > Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
> 
> Null values still don't work. I'll make the necessary changes by forking from your branch.
> 

I have only made the changes to BE, to confirm if the changes were appropriate. If they are, I will make the changes to FE too.

2024-12-09 11:36 UTC, erenfn commented
- They look fine, but it would be better if you could refactor the validations in the controller into helper like this:

```
const validateSetConfig = [
  check('apiKey')
    .optional()
    .isString().withMessage('API Key should be a string')
    .trim()
    .notEmpty().withMessage('API Key should not be empty'),
  
  check('serverUrl')
    .optional()
    .isString().withMessage('Server URL should be a string')
    .trim()
    .custom((value) => {
      if (value) {
        const result = validateServerUrl(value);
        if (!result.valid) {
          throw new Error(result.errors.join(' '));
        }
      }
      return true;
    })
];
```

I didn't test if it works; it's just to give you an idea.

- Also we can delete unused url regexes in constants

2024-12-09 11:44 UTC, d02ev commented
> - They look fine, but it would be better if you could refactor the validations in the controller into helper like this:
> 
> ```
> const validateSetConfig = [
>   check('apiKey')
>     .optional()
>     .isString().withMessage('API Key should be a string')
>     .trim()
>     .notEmpty().withMessage('API Key should not be empty'),
>   
>   check('serverUrl')
>     .optional()
>     .isString().withMessage('Server URL should be a string')
>     .trim()
>     .custom((value) => {
>       if (value) {
>         const result = validateServerUrl(value);
>         if (!result.valid) {
>           throw new Error(result.errors.join('|'));
>         }
>       }
>       return true;
>     })
> ];
> ```
> 
> I didn't test if it works; it's just to give you an idea.
> 
> - Also we can delete unused url regexes in constants

Sure, will make the necessary changes to both FE and BE.

2024-12-16 19:20 UTC, erenfn commented
Hey, we are near to 1.0 release, and we have decided to remove API_KEY; Server URL will stay. Sorry for that change. Can you remove API_KEY both on backend and frontend, and keep Server url?

2024-12-16 19:38 UTC, erenfn commented
Also this brnach has 60 commits. It is possible to create a new branch from develop and move the changes you made about server url there?

2024-12-16 19:43 UTC, d02ev commented
> Hey, we are near to 1.0 release, and we have decided to remove API_KEY; Server URL will stay. Sorry for that change. Can you remove API_KEY both on backend and frontend, and keep Server url?

Sure, will do.

2024-12-16 19:44 UTC, d02ev commented
> Also this brnach has 60 commits. It is possible to create a new branch from develop and move the changes you made about server url there?

I was thinking of same. I will close this PR, and raise a new one through a new branch

2024-12-16 19:44 UTC, closed without merging