Fix #341 : Update CustomTextField for full-width support
bluewave-labs/bluewave-onboarding pull request #353
Opened 2024-11-28 18:31 UTC by saksham-malhotra-27

**Issue:**  
The _CustomTextField_ component does not handle width properly. Specifically, it lacks support for stretching to 100% width.

**Implementation:**  
+ Modified the _CustomTextField.jsx_ file to add a new _fullWidth_ prop as a _boolean_.
+ Replaced the previous _TextFieldWidth_ prop with the new _fullWidth_ prop to manage the width behavior.
+ The _fullWidth_ boolean simplifies the implementation by directly applying a 100% width when set to true, making it more intuitive and easier to use.

2024-11-28 18:36 UTC, saksham-malhotra-27 commented on frontend/src/components/TextFieldComponents/CustomTextField/CustomTextField.jsx
> +        fullWidth={fullWidth}
Yes, you're absolutely right! One thing to keep in mind is that we can't fully guarantee that other custom CSS won’t override MUI's styles. To prevent conflicts, it's best to ensure both the _sx_ width and _fullWidth_ prop have consistent values when _fullWidth_ is true

2024-12-02 00:49 UTC, erenfn requested changes
Right now login page looks like this. (default fullWidth)

![image](https://github.com/user-attachments/assets/8e11f4f5-8ce0-4580-9591-08106adf30f7)

And this is CreatePopupPage.jsx with fullWidth=true

![image](https://github.com/user-attachments/assets/e5bd8229-ad59-4b27-9195-d07f4a943f88)

Maybe fullWidth is not what we are looking for. Also please test your code.

2024-12-02 15:16 UTC, saksham-malhotra-27 commented
@erenfn  Could you elaborate on the issue ? I understand your point about full width, but what other concerns are you referring to related to the full-width aspect ?
Also, note that FullWidth here is just a flag for the component. Its behavior depends on whether the parent container is set to full-screen width. For example:
+ **Parent div**: Width set to 50%.
+ **Child div**: If set to 100% due to the _FullWidth_ flag, it would still only take up 50% of the screen width since it is relative to the parent container.

2024-12-02 19:15 UTC, erenfn commented
I know. The thing is that we wrap the text field in a div, and I believe that is where this problem occurs. Also, you can clearly see from the second image that it doesn't take up 100% of the space of the parent.

2024-12-10 15:57 UTC, erenfn commented
@saksham-malhotra-27 Any updates?

2024-12-10 16:27 UTC, saksham-malhotra-27 commented
Hey @erenfn ! I got a bit busy, but I came across this:
### Problem:
In the first _CustomTextField_, I explicitly applied _fullWidth_ as true. However, in the second one, I didn’t:
![image](https://github.com/user-attachments/assets/c292437e-f7a7-498a-8b21-e67f6883bc7a)

As a result, the views turned out like this:
![image](https://github.com/user-attachments/assets/62338a1b-73a7-41e0-9fa9-3de59111a6f1)

This happens because the default value of _**fullWidth**_ is set to false. Even if _**TextFieldWidth**_ is set to 'full', the _fullWidth_ prop still falls back to its default value:
![image](https://github.com/user-attachments/assets/2e1823a9-1f6c-4531-88e0-127c1a32608d)

### Solution: 
Here are two possible approaches to resolve this:

1. Set _fullWidth's_ default value to true
This way, it will always default to true, and you’ll need to explicitly set it to false when needed.

2. Update the logic in _CustomTextField_
Configure it so that if TextFieldWidth is 'full' and fullWidth is not explicitly passed, it automatically defaults to true. In all other cases where fullWidth isn’t provided, it defaults to false.

My Recommendation:
I suggest going with the second approach for better flexibility and handling edge cases.

Let me know your thoughts on this! Once you approve, I’ll implement the changes and commit them. Apologies again for the delay—I’ll ensure this gets finished within a day. 😊

2024-12-10 16:40 UTC, saksham-malhotra-27 commented
Hey! To implement the changes quickly and effectively, I went ahead with the second approach by doing the following:
![image](https://github.com/user-attachments/assets/ce3cb9f4-b5e3-44bb-8edf-94a47a799672)

Now, the decision for whether the text field should occupy full width is based on this computed full width property.

I also included "stretch" to account for scenarios where terms commonly associated with flexible layouts, like "stretch", might be used.

Result:
![image](https://github.com/user-attachments/assets/715dd805-0a36-4f56-a33a-dca87242115d)

2024-12-10 18:36 UTC, erenfn commented
Thanks, the second approach makes sense. Could you also check other parts (Like `/popup/create`, `/banner/create`, and `settings`) to ensure they work as intended?

2024-12-10 23:59 UTC, saksham-malhotra-27 commented
Hey @erenfn! I've checked everything, and it all seems to be working fine on my end. Many of the components use predefined widths like 241px, so it doesn't make much of a difference. Additionally, when **fullWidth** is set to true, it works as expected.

Could you please review the code once?

2024-12-11 19:43 UTC, erenfn requested changes
- This is when I set fullWidth=true for the second text field

![image](https://github.com/user-attachments/assets/6531f567-ab98-4786-a9da-5cb0ac5de622)

- This is when I set the width of the parent div of the TextField 100% for the second text field:

![image](https://github.com/user-attachments/assets/10d1e3e2-122e-4ad7-bba4-55d00827f84c)

You also have to set the width of the outer div element. The screenshots are taken from /popup/create page by zooming out

2024-12-12 00:52 UTC, saksham-malhotra-27 commented
Alright ! working on it, 
Just confirming: Should I set the parent div's width to **100%** for all or only for the **/popup/create** ?

2024-12-12 01:00 UTC, erenfn commented
It should be set to 100% when fullWidth=true

2024-12-12 02:36 UTC, saksham-malhotra-27 commented
Alright! Will see the issue today.

2024-12-12 20:04 UTC, saksham-malhotra-27 commented
Hey @erenfn ! 
### Approach 1 
1. One way to fix the "create popup" design is by adding a shared _fullWidth_ state in the component. This would result in the following design:
![image](https://github.com/user-attachments/assets/b740d528-b3ba-4722-9e91-84f202eb715a)

2. This change would look like this after implementation:
![image](https://github.com/user-attachments/assets/56729388-fa94-44d8-a751-d23415785041)

However, there are some limitations to consider as it's similar to being hard coded. The "Banner Create", "Popup Create", and "CodeTab" under Settings all need similar adjustments. Although we currently use a fixed width for all three.

### Approach 2 

1. Modify the container styling in the above mentioned component's individual SCSS files.

![image](https://github.com/user-attachments/assets/e683a4cf-1e72-4a0a-9c89-6d45efb81fcd)

2. By adding width: 100% to the container and wrapping the custom text fields in a div with width: 100%, we can ensure that when fullWidth is used, it correctly assigns the width to 100%.
![image](https://github.com/user-attachments/assets/ef09c8c7-9c96-4014-b0fe-509130c85e46)

3. Result : 
![image](https://github.com/user-attachments/assets/71ea34b7-fe6d-411f-88aa-a19d74b67739)

According to me the 2nd approach is reliable and better than the first one . Let me know your thoughts, I'll change the code accordingly.

2024-12-12 23:05 UTC, erenfn commented on frontend/src/components/TextFieldComponents/CustomTextField/CustomTextField.jsx
>      <div style={style}>
By the 'parent div' I meant this div. You shouldn't change /popup/create. Just change this file

2024-12-13 06:10 UTC, saksham-malhotra-27 commented on frontend/src/components/TextFieldComponents/CustomTextField/CustomTextField.jsx
>      <div style={style}>
Got your point! It’s much easier and more reliable to change the styling this way.

What I’ve added is that if **_computedFullWidth_** is true, a class will be added to the parent div that sets its width to 100%.
![image](https://github.com/user-attachments/assets/c827ef5d-444a-4cc4-9eeb-4dabc940c7ae)

Is this what you meant?

2024-12-13 06:11 UTC, saksham-malhotra-27 commented on frontend/src/components/TextFieldComponents/CustomTextField/CustomTextField.jsx
>      <div style={style}>
It's working fine with the _**popup/create**_.

2024-12-13 17:35 UTC, saksham-malhotra-27 commented on frontend/src/components/TextFieldComponents/CustomTextField/CustomTextField.jsx
>      <div style={style}>
Hey @erenfn! If you have some time, could you take a look at or review my changes?

2024-12-14 00:09 UTC, erenfn commented on frontend/src/components/TextFieldComponents/CustomTextField/CustomTextField.jsx
>      <div style={style}>
Instead of using classname can you merge it with style={style}?

2024-12-14 05:03 UTC, saksham-malhotra-27 commented on frontend/src/components/TextFieldComponents/CustomTextField/CustomTextField.jsx
>      <div style={style}>
Hey ! 
This can be implemented with style as:
![image](https://github.com/user-attachments/assets/dc56614f-4040-49bf-96a7-7ec029f05369)

2024-12-16 18:04 UTC, erenfn commented on frontend/src/components/TextFieldComponents/CustomTextField/CustomTextField.jsx
>      <div style={style}>
Can you push these changes?

2024-12-17 02:51 UTC, saksham-malhotra-27 commented
Hey @erenfn ! I have pushed the changes.

2024-12-17 12:49 UTC, erenfn approved these changes

2024-12-17 12:58 UTC, merged