Issue #288 Moved mui-root stylings in various css files to src/assets…
bluewave-labs/bluewave-onboarding pull request #354
Opened 2024-11-29 08:34 UTC by Bugbuster2004

**Description**:
This pull request addresses issue **#288** by consolidating _MUI-specific component styles from various CSS_ files into the centralized _theme.jsx_ file. This approach ensures better maintainability, consistency, and scalability across the application’s design system.

**Key Changes Made:**

_Migration of Styles:_
Moved the **MuiTab-root styles** from _src/components_ to the _theme.jsx_ file under the overrides section.
Reviewed and migrated similar MUI-related component styles from other CSS files to the centralized theme configuration.
Theme Customization:

Added custom **typography configurations such as font-family, font-size, font-style, font-weight, and line-height for MuiTab-root** and other applicable components in the theme.
Ensured that the styles align with the Inter font family as per the design requirements.

Code Cleanup:
Removed redundant CSS files or declarations for MUI components that are now covered under the _theme.jsx_ configuration.
Refactored the CSS file for HeadingTabs to retain only non-MUI-specific stylings.

Branch Specifics:
All changes have been made on the develop branch, which is the most up-to-date branch for this project.

2024-12-01 07:45 UTC, Bugbuster2004 commented on frontend/src/assets/theme.jsx
>      },
i have applied the changes suggested by you

2024-12-01 08:18 UTC, Bugbuster2004 commented on frontend/src/assets/theme.jsx
> +            backgroundColor: "#F9FAFB",
i have made the css variables changes as suggested just wanted to confirm do i need to do the same for borders also?
![image](https://github.com/user-attachments/assets/63bf5ca1-9a51-4238-baa7-2b43bc16de93)

2024-12-02 00:31 UTC, erenfn requested changes
Can you also remove related stylings from other css files as mui-root is now handled here?

2024-12-02 00:31 UTC, erenfn commented on frontend/src/index.css
> +  --color-black: #000;
Same variables are also in `variables.css`
Is it possible to get rid of one of them?

2024-12-02 01:57 UTC, Bugbuster2004 commented on frontend/src/index.css
> +  --color-black: #000;
we can do one thing that 
![image](https://github.com/user-attachments/assets/64bf27fc-0d9e-471d-bee9-64bb2c666d40)
we can shift these variable color to variable.css and remove it from index.css.
Kindly Confirm if i am thinking right , open to suggestions

2024-12-02 05:13 UTC, Bugbuster2004 commented on frontend/src/index.css
> +  --color-black: #000;
made all the changes as requested

2024-12-02 19:11 UTC, erenfn requested changes

2024-12-02 19:11 UTC, erenfn commented on frontend/src/components/Button/ButtonStyles.css
> -.primary.MuiButton-root {
You may have understood the task wrong. You shouldn't delete this file or delete classes like these. `.primary.MuiButton-root` is not the same as `.MuiButton-root`. We are looking for the latter to refactor. all others should stay in place

2024-12-03 01:50 UTC, Bugbuster2004 commented on frontend/src/components/Button/ButtonStyles.css
> -.primary.MuiButton-root {
hey @erenfn i undertsood your issue 
but i have to ask that
1. 
![image](https://github.com/user-attachments/assets/49299e12-1f8d-45ea-8f0b-48650c27049a)
in this image the primary things is handled using the contained primary 
![image](https://github.com/user-attachments/assets/86601c72-485c-4849-85ad-375534e9fa9f)

so are you saying that the contained primary logic is extra  and i should remove that or is there a still difference in both

2024-12-04 14:09 UTC, erenfn requested changes
It may work, but I cannot test it because this error occurs during the build process:
```
Uncaught Error: MUI: Unsupported `var(--main-purple)` color.
The following formats are supported: #nnn, #nnnnnn, rgb(), rgba(), hsl(), hsla(), color().
```
Please test your code

2024-12-10 15:58 UTC, erenfn commented
@Bugbuster2004 Any updates?

2024-12-10 16:02 UTC, Bugbuster2004 commented
hey @erenfn  apologies for keeping u waiting , got stuck in some college work , i will work on this tonight and will update you by tomorrow morning. (Indian time)

2024-12-10 16:04 UTC, erenfn commented
Hey, that's fine. Thanks for letting me know

2024-12-11 06:32 UTC, Bugbuster2004 commented
hey @erenfn  i have made the changes 
![image](https://github.com/user-attachments/assets/d1d9d6ff-da9c-436c-8a54-2cf0d07ae049)
this is the build status
should i send the PR or are there changes to be suggested like regarding these warnings

2024-12-11 19:32 UTC, erenfn commented
You can disregard the warnings and send the PR

2024-12-13 16:55 UTC, Bugbuster2004 commented
Hello @erenfn 

I have raised the PR; however, I was unable to test the frontend code as the backend was not functioning as expected due to some issues with the Docker setup. Though the build process completed successfully without any errors.  

If needed, please let me know, and I would appreciate your guidance in resolving the backend setup process.  

Thank you!

2024-12-15 22:54 UTC, erenfn requested changes
The colors don't work correctly. 

![image](https://github.com/user-attachments/assets/3cb607ab-e44e-4bd0-a3f1-eaaf796a6f15)

The things we defined on the css files are all lost

![image](https://github.com/user-attachments/assets/dbe03aa2-dca4-4c64-80d2-def2bdd6e7ad)

Maybe it is just better to stick to the original issue and just refactor the mui-root styles that doesn't have an extra class

2024-12-16 07:39 UTC, Bugbuster2004 commented
hey @erenfn i got your point , i have to refactor the code again by sticking to the original issue it will take me some days to do that as i have my exams going on currently.

2024-12-24 19:44 UTC, erenfn commented
Hey, it has taken a while, so we solved it with #430 . Thanks for your time!

2024-12-24 19:44 UTC, closed without merging