Fix/379 button design in the home page
bluewave-labs/bluewave-onboarding pull request #398
Opened 2024-12-18 13:26 UTC by MandeepPaul

## Describe your changes

Briefly describe the changes you made and their purpose.

## Issue number

#396 

## Please ensure all items are checked off before requesting a review:

- [ ] I deployed the code locally.
- [ ] I have performed a self-review of my code.
- [ ] I have included the issue # in the PR.
- [ ] I have labelled the PR correctly.
- [ ] The issue I am working on is assigned to me.
- [ ] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [ ] I made sure font sizes, color choices etc are all referenced from the theme.
- [ ] My PR is granular and targeted to one specific feature.
- [ ] I took a screenshot or a video and attached to this PR if there is a UI change.

## Preview
![Screenshot 2024-12-18 071641](https://github.com/user-attachments/assets/dfd31c42-e69e-44eb-bd43-b8f5d85e1220)

2024-12-18 15:33 UTC, gorkem-bwl commented
Thanks. A few notes.

- Can you check the radiuses of the boxes on top and at the bottom? They are not the same.
- Wording should be same as in Figma (e.g instead of hint views, we have banner views). 
- Make sure the fonts reflect the same color in Figma
- If the mouse is hovered on a card, does it look like the one in "Create a new banner"?

2024-12-19 14:47 UTC, MandeepPaul commented
My bad! I initially thought I only needed to update the buttons, but I have now updated the StatisticCards as well. Please find the attachment - the **'Create a a new banner'** button shows the hover state in it.

![image](https://github.com/user-attachments/assets/b385a19f-17d3-4dd1-9432-7493473d18e8)

2024-12-19 15:03 UTC, erenfn commented
Can you disable formatting for all files, and just enable it for the current file?

2024-12-19 16:43 UTC, erenfn commented
It would be great if you can revert the last commit (I believe that's where all files are formatted) and just update the relevant files

2024-12-20 14:49 UTC, MandeepPaul commented
Should be good now!

![image](https://github.com/user-attachments/assets/b385a19f-17d3-4dd1-9432-7493473d18e8)

2024-12-21 00:16 UTC, gorkem-bwl commented
Hi Mandeep. I couldn't find an answer/ref to the question below. Can you let me know? 

> If the mouse is hovered on a card, does it look like the one in "Create a new banner"?

2024-12-21 01:41 UTC, MandeepPaul commented on frontend/src/scenes/dashboard/HomePageComponents/CreateActivityButton/CreateActivityButton.jsx
> +      sx={{
copy! I will update in next commit

2024-12-21 01:47 UTC, MandeepPaul commented
> Yes Gorkhem, the middle card in the screenshot attached is in hover state.  
>> Hi Mandeep. I couldn't find an answer/ref to the question below. Can you let me know?
> > > If the mouse is hovered on a card, does it look like the one in "Create a new banner"?

2024-12-21 07:08 UTC, gorkem-bwl commented
> > Yes Gorkhem, the middle card in the screenshot attached is in hover state.
> > > Hi Mandeep. I couldn't find an answer/ref to the question below. Can you let me know?
> > > > If the mouse is hovered on a card, does it look like the one in "Create a new banner"?

Thank you.

2024-12-22 08:41 UTC, MandeepPaul commented
I have rewritten the commit history and removed unnecessary formatted files. Please refer to the attachment for the updated UI, where the 'Create a New Helper Link' button now shows the hover state.

## Preview 
![onboarding-ui-update](https://github.com/user-attachments/assets/7cc861f2-c425-45bf-83a1-c0cfc61afe20)

2024-12-22 15:12 UTC, gorkem-bwl commented
UI wise that looks good!

2024-12-23 00:13 UTC, erenfn requested changes

2024-12-23 00:13 UTC, erenfn commented on frontend/src/scenes/dashboard/Dashboard.jsx
> +          frontSkeletonProps={{
Hey, thanks for removing the code formatting for other files. The UI looks great! The only refactoring we could make here is to move these styles into a new file within the Skeletons folder and import them into `BaseSkeleton.jsx.`

An example usage of this might be:
` <BaseSkeleton guideType='popup'>`

2024-12-23 01:07 UTC, MandeepPaul commented on frontend/src/scenes/dashboard/Dashboard.jsx
> +          frontSkeletonProps={{
Great suggestion, I just updated it!!

2024-12-23 22:03 UTC, erenfn submitted a review, later dismissed
looks good!

2024-12-24 01:25 UTC, erenfn approved these changes

2024-12-24 01:25 UTC, erenfn commented
@coderabbit resolve

2024-12-24 01:26 UTC, merged