405-linkid-potential-bug
bluewave-labs/bluewave-onboarding pull request #412
Opened 2024-12-21 01:08 UTC by DeboraSerra

## Describe your changes

Briefly describe the changes you made and their purpose.

## Issue number

Mention the issue number(s) this PR addresses (e.g., #123).

## Please ensure all items are checked off before requesting a review:

- [ ] I deployed the code locally.
- [ ] I have performed a self-review of my code.
- [ ] I have included the issue # in the PR.
- [ ] I have labelled the PR correctly.
- [ ] The issue I am working on is assigned to me.
- [ ] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [ ] I made sure font sizes, color choices etc are all referenced from the theme.
- [ ] My PR is granular and targeted to one specific feature.
- [ ] I took a screenshot or a video and attached to this PR if there is a UI change.

2024-12-21 17:08 UTC, erenfn requested changes
I don't get that error anymore in the db anymore. However, I came across this new error: It occurs when you edit a helper link and delete one of its links:

![image](https://github.com/user-attachments/assets/18ed9afa-e96b-4dc7-8e56-95820123b177)
![image](https://github.com/user-attachments/assets/b797bf00-bb41-43a1-b9a7-21d3ce1d46f0)

2024-12-22 17:18 UTC, swoopertr commented on frontend/src/components/Links/Settings/Settings.jsx
s object imported from "./Settings.module.scss" is may create some inconvenience. It is look like a magical "s".
It should renamed like "ComponentStyle" or "Style". Something like that

2024-12-23 23:53 UTC, erenfn commented
I still get this error in the console. It happens when you add a link, delete it, and then clicking save. My guess is that we add that link to the "links to be deleted" list and then try to delete it. However, this error occurs because we haven't created it in the first place. The links that are created before clicking save shouldn't be added to the `deletedLinks` links afterwards

![image](https://github.com/user-attachments/assets/136def84-e3d7-40de-8fde-5e57c0e4bf3e)

2024-12-24 14:31 UTC, erenfn approved these changes

2024-12-24 14:35 UTC, erenfn requested changes
The other bug is gone.

However, adding two url's with the same title and deleting one of them deletes both of them. We should fix it

![image](https://github.com/user-attachments/assets/38e26b79-7ccd-47e3-85e8-d1e69d974738)
![image](https://github.com/user-attachments/assets/225b2417-b55e-4657-83f2-bb9a75e2c15b)
![image](https://github.com/user-attachments/assets/fc6fde24-a43e-499d-ba04-8c198c2fc6da)

2024-12-24 14:56 UTC, erenfn approved these changes

2024-12-24 14:56 UTC, merged