Issue 63: fixed issue 63 and added createdBy to popup table
bluewave-labs/bluewave-onboarding pull request #64
Opened 2024-06-05 22:43 UTC by erenfn

2024-06-06 05:02 UTC, uparkalau requested changes
It looks like work in progress. you have to close this PR or finish code

2024-06-06 05:02 UTC, uparkalau commented on backend/src/controllers/popupController.js
>              console.log(err);
delete console log

2024-06-06 05:02 UTC, uparkalau commented on backend/src/controllers/popupController.js
>          // Check if required fields are present and not null
do not need this comments

2024-06-06 05:02 UTC, uparkalau commented on backend/src/models/Popup.js
> +const User = require('./User'); // Adjust the path if necessary
delete comments

2024-06-06 11:13 UTC, erenfn commented
fixed

2024-06-09 04:14 UTC, uparkalau approved these changes

2024-06-09 04:14 UTC, uparkalau commented
You can merge it

2024-06-09 19:52 UTC, swoopertr commented on backend/src/controllers/popupController.js
>              if (isNaN(id) || id.trim() === '') {
@uparkalau we could have a validator function to check types for each field.

2024-06-10 13:47 UTC, uparkalau approved these changes
We can merge it into the develop

2024-06-13 06:08 UTC, uparkalau submitted a review, later dismissed

2024-06-16 05:45 UTC, uparkalau approved these changes

2024-06-16 23:03 UTC, merged