50 refactor logos component to make it reusable
bluewave-labs/bluewave-onboarding pull request #65
Opened 2024-06-06 03:01 UTC by SevinjFeyzi

2024-06-06 04:58 UTC, uparkalau requested changes
review your code again. this is a lot of merge artifacts

2024-06-06 04:58 UTC, uparkalau commented on frontend/src/components/Logo/Logo.jsx
> +<<<<<<< Updated upstream
review your code . what is ">>>>>>> Stashed changes" you did not test your code after merge.

2024-06-06 11:39 UTC, erenfn requested changes

2024-06-06 11:39 UTC, erenfn commented on frontend/src/.App.jsx.swo
do not push these files

2024-06-06 11:39 UTC, erenfn commented on frontend/src/.App.jsx.swp
Same. Do not push these files

2024-06-06 11:39 UTC, erenfn commented on frontend/src/components/Logo/TestLogo.jsx
Is this file going to be used? If it is just for testing remove it.

2024-06-06 11:39 UTC, erenfn commented on frontend/src/App.jsx
> +import TestLogo from "./components/Logo/TestLogo";
If TestLogo is just for testing, use the actual Logo instead. And I am not sure what Logo is doing in App.jsx

2024-06-07 03:32 UTC, uparkalau requested changes

2024-06-07 03:32 UTC, uparkalau commented on frontend/src/scenes/home/Home.jsx
> +      console.log('Home logo object:', logo);
Delete all console.log

2024-06-07 03:37 UTC, SevinjFeyzi commented on frontend/src/scenes/home/Home.jsx
> +      console.log('Home logo object:', logo);
Done!

2024-06-07 03:40 UTC, uparkalau requested changes

2024-06-07 03:40 UTC, uparkalau commented on frontend/src/components/Logo/Logo.jsx
> +  console.log('Logo prop:', logo);
Check all code please

2024-06-07 03:51 UTC, uparkalau approved these changes
You can merge your code into develop

2024-06-09 18:12 UTC, swoopertr commented on frontend/src/components/Logo/Logo.jsx
This logo component props may have "width" and "height" in the propTypes.

2024-06-09 18:14 UTC, swoopertr commented on frontend/src/components/Logo/LogoStyles.css
logoImage class never used in project. If it won't used. You can delete.

2024-06-09 18:17 UTC, swoopertr commented on frontend/src/scenes/home/Home.jsx
I think this is the usage how to use logo component and sending object as a props. 
It looks like giant logo in the screen :). We definitely need width and height in props.

2024-06-09 18:20 UTC, swoopertr commented on frontend/src/App.jsx
in 20th row <Logo/> component doing nothing. You can remove it or use properly.

2024-06-09 19:18 UTC, uparkalau commented on frontend/src/App.jsx
> +<Logo/>
delete it from here

2024-06-11 14:34 UTC, erenfn commented on frontend/src/components/Logo/LogoStyles.css
> +    height: 75px;
For later, you may want to do the Logo more adaptable to different containers or window sizes and not hardcode the dimensions (px)

But for now it is fine

2024-06-11 14:54 UTC, merged