Feature/53 refactor buttons to button component to make it reusable
bluewave-labs/bluewave-onboarding pull request #70
Opened 2024-06-11 20:28 UTC by SimerdeepSinghGrewal

I've removed the hard-coded button files and added button.jsx file to accept (text, onClick, variant, className, style, sx) via props
added styles file with all the six hard-coded button's style.
tested the buttons as well for accepting props and display styles.

2024-06-11 22:26 UTC, erenfn commented on frontend/src/components/Button/ButtonStyles.css
> +:root {
Can you try to use the colors on styles/variables.css and add new ones if they don't exist there. Don't use :root in this file. Also you don't have to create variables for colors like 'grey' and 'white'

The reason why we don't use :root here is that it affects every css file. It would be better if we addressed :root under a more "global" file, which in this case is variables.css

2024-06-11 22:27 UTC, erenfn commented on frontend/src/components/Button/ButtonStyles.css
> +:root {
other than that it looks good

2024-06-11 22:29 UTC, SimerdeepSinghGrewal commented on frontend/src/components/Button/ButtonStyles.css
> +:root {
ok, thanks for that , i will do it tomorrow.

2024-06-12 14:48 UTC, SimerdeepSinghGrewal commented on frontend/src/components/Button/ButtonStyles.css
> +:root {
done the final edit for css, used colors from styles/variables.css and removed :root from ButtonStyles.css

2024-06-13 06:02 UTC, uparkalau commented on frontend/src/components/Button/ButtonStyles.css
> +  color: rgba(128, 128, 128, 0.9);
Can you do not use rgba if it possible use constants if you can implement it

2024-06-13 06:04 UTC, uparkalau commented on frontend/src/scenes/dashboard/index.jsx
> +import TestButton from "../../components/Button/TestButton";
delete your testButton this is just for your test purpose when you confident all working  well delete it.

2024-06-13 06:05 UTC, uparkalau requested changes
Please resolve all comments and then you can merge it

2024-06-13 09:18 UTC, erenfn commented on frontend/src/components/Button/ButtonStyles.css
> +  color: rgba(128, 128, 128, 0.9);
MUIButton is kinda annoying in terms of applying css. The easiest way to apply styles is by using sx. Only the button needs some css. Can't I just leave it like this?

2024-06-13 14:20 UTC, SimerdeepSinghGrewal commented on frontend/src/components/Button/ButtonStyles.css
> +  color: rgba(128, 128, 128, 0.9);
changed all rgba colors to hex code colors

2024-06-13 14:20 UTC, SimerdeepSinghGrewal commented on frontend/src/scenes/dashboard/index.jsx
> +import TestButton from "../../components/Button/TestButton";
done.

2024-06-17 12:51 UTC, erenfn commented
When buttons are "active," they do not have an outline, as shown in the Figma file. For example, for the error button:active, you can add the following style: border: 4px solid #FCCED7; Additionally, when a button is active, the border-radius is not applied. It becomes a rectangle.

Also I am not sure if we want these to be a propType:  
  style: PropTypes.object,
  sx: PropTypes.object,

The style of the button should be determined by the inner logic in the jsx file.

2024-06-18 19:39 UTC, uparkalau approved these changes

2024-06-18 20:09 UTC, merged

2024-06-18 20:11 UTC, erenfn commented
@uparkalau className should be optional right? It is just for additional styling. What I understand from this task is the default styling should be determined by the type of the button i.e. error, primary, secondary etc.