feat: Home page components
bluewave-labs/bluewave-onboarding pull request #71
Opened 2024-06-12 11:44 UTC by erenfn

2024-06-13 05:54 UTC, uparkalau commented on frontend/src/components/HomePageComponents/CreateActivityButton/CreateActivityButton.jsx
> +      sx={{
separate it into theme file or css, use contants for colors.

2024-06-13 05:55 UTC, uparkalau commented on frontend/src/components/HomePageComponents/DateDisplay/DateDisplay.jsx
> +// DateDisplay.propTypes = {
delete if do not need it. But better to use props type

2024-06-13 05:57 UTC, uparkalau commented on frontend/src/components/HomePageComponents/StatisticCards/StatisticCards.module.scss
> +    border: 1px solid #EAECF0;
use constants for the color definition

2024-06-13 05:59 UTC, uparkalau commented on frontend/src/scenes/dashboard/Dashboard.jsx
> +                    <CreateActivityButton
create a list component for this repetitions

2024-06-13 05:59 UTC, uparkalau commented on frontend/src/scenes/dashboard/Dashboard.jsx
> +                    <StatisticCard
Create a static cards list component

2024-06-13 06:00 UTC, uparkalau requested changes
Jus a little bit of refactoring and then you can merge it

2024-06-13 09:19 UTC, erenfn commented on frontend/src/components/HomePageComponents/CreateActivityButton/CreateActivityButton.jsx
> +      sx={{
MUIButton is kinda annoying in terms of applying css. The easiest way to apply styles is by using sx. Only the button needs some css. Can't I just leave it like this?

2024-06-17 05:13 UTC, uparkalau approved these changes
Looks good you can merge it.

2024-06-17 09:09 UTC, merged