Develop the avatar component #67
bluewave-labs/bluewave-onboarding pull request #84
Opened 2024-06-24 14:10 UTC by SevinjFeyzi

2024-06-25 13:59 UTC, erenfn requested changes
You still have the same issue. 
![image](https://github.com/bluewave-labs/bluewave-onboarding/assets/81182796/8e20b76d-930f-404a-9abb-e3c952927392)
Did you make the changes that I pointed out?

2024-06-25 14:03 UTC, erenfn commented
import React from 'react';
import PropTypes from 'prop-types';
import './AvatarStyles.css';


const Avatar = ({ src, alt, size }) => {
    return (
        <div className={avatar-container}>
            <img src={src} alt={alt} className={ ${size}}/>
        </div>
    );}

Avatar.propTypes = {
    src: PropTypes.string.isRequired,
    alt: PropTypes.string.isRequired,
    size: PropTypes.oneOf(['small','medium', 'large']),
    className: PropTypes.string,
};

export default Avatar;

2024-06-25 14:03 UTC, erenfn commented
:root {
    --avatar-small: 24px;
    --avatar-medium: 40px;
    --avatar-large: 48px;
    --avatar-border-color: #000000;
  }

  .avatar-container {
    display: inline-flex;
    justify-content: center;
    align-items: center;
    border-radius: 50%;
    overflow: hidden;
    box-sizing: border-box; 
    border-radius: 50%; 
    margin-right: 10px; 
    border: 0.5px solid #000000; 
    object-fit: cover;
  }

  .small {
    width: var(--avatar-small);
    height: var(--avatar-small);
  }

  .medium {
    width: var(--avatar-medium);
    height: var(--avatar-medium);
  }

  .large {
    width: var(--avatar-large);
    height: var(--avatar-large);
  }

  .avatar-container.border {
    border: 0.5px solid var(--avatar-border-color);
  }

2024-06-25 21:04 UTC, erenfn requested changes

2024-06-25 21:04 UTC, erenfn commented on frontend/src/scenes/home/Home.jsx
> +    const logo = {
This must be deleted

2024-06-25 21:04 UTC, erenfn commented on frontend/src/components/Header/Header.jsx
> +                <Avatar src="/vendetta.png" alt="User" size="medium "
size prop doesn't work properly

2024-06-25 21:04 UTC, erenfn commented on frontend/src/components/Header/Header.jsx
> +                   className="user-picture" />
className shouldn't reference a css file other than a style from Header.css (since we are in Header.jsx) this className should be for additional styling not default styling. As I said use 'classnames' library in Avatar.js, to merge the 'default styling' and this 'additional styling'

2024-06-26 13:21 UTC, erenfn submitted a review, later dismissed

2024-06-26 19:00 UTC, erenfn requested changes
You don't have to delete propTypes, they can stay. Also don't use defaultProps as:

` Warning: Avatar: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

Check warnings before pushing your code.

2024-06-27 14:57 UTC, erenfn submitted a review, later dismissed

2024-06-27 15:01 UTC, uparkalau commented on frontend/src/components/Avatar/Avatar.jsx
> +    alt: PropTypes.string.isRequired,
Alt is not required

2024-07-02 11:45 UTC, erenfn approved these changes

2024-07-03 03:52 UTC, merged