Feature/86 refactor text field component
bluewave-labs/bluewave-onboarding pull request #89
Opened 2024-06-29 02:33 UTC by thomastepi

Refactored TextFieldComponents to enhance customization by introducing the CustomTextField component. This change allows each rendered text field to be modified with specific props. Additionally, PropTypes have been added to CustomTextField to enforce prop validation.

**Changes Made:**

1.  Implemented CustomTextField component to replace direct usage of MUI TextField.
2.  Introduced PropTypes to validate props passed to CustomTextField.
3.  Created test cases to verify component functionality.

**Reason for Changes:**

To streamline component reusability and maintain consistency in prop usage throughout the application.

2024-07-02 11:44 UTC, erenfn requested changes
- The default font size should be 13px.
- Also, please adjust the height of the text field accordingly.
- It would be very helpful if you could provide a brief explanation of the prop types as a block comment in the file.
- Some details, such as shadows, were missing. You can find these in the Style Guide Figma file.
- It would be good if you could specify the default parameters.

Other than that, good work!

2024-07-02 11:51 UTC, erenfn commented on frontend/src/tests/scenes/login/LoginPage.test.jsx
> +import { describe, it, expect } from "vitest";
Also why do you have these files? I think they are not merged into the develop branch

2024-07-05 00:01 UTC, thomastepi commented
> * The default font size should be 13px.
> * Also, please adjust the height of the text field accordingly.
> * It would be very helpful if you could provide a brief explanation of the prop types as a block comment in the file.
> * Some details, such as shadows, were missing. You can find these in the Style Guide Figma file.
> * It would be good if you could specify the default parameters.
> 
> Other than that, good work!

I have implemented the changes you recommended and also updated the file to align with the styling in the Figma guide. thanks

2024-07-06 09:24 UTC, swoopertr commented on frontend/src/components/TextFieldComponents/CustomTextField.jsx
> +// Explanation of the PropTypes used in this file
those descriptions should be in readme.md file with an appropriate explanation.

2024-07-06 09:24 UTC, swoopertr commented on frontend/src/components/TextFieldComponents/CustomTextField.jsx
> +      <TextField
this component usage is too complex, hard to understand, and difficult to modify. Please split the more basic functions or objects.

2024-07-06 09:24 UTC, swoopertr commented on frontend/src/components/TextFieldComponents/TextFieldComponents.jsx
> +          endAdornment=<ErrorOutlineIcon color="error" />
What are the colors ? "error" error color?
can you make the selection with enum like; ErrorOutlineIcon.Color.Error

2024-07-08 18:16 UTC, uparkalau requested changes

2024-07-09 13:38 UTC, thomastepi commented on frontend/src/components/TextFieldComponents/CustomTextField/CustomTextField.jsx
> +CustomTextField.propTypes = {
should i delete the prop types

2024-07-20 22:50 UTC, erenfn commented on frontend/src/components/TextFieldComponents/CustomTextField/CustomTextField.jsx
> +CustomTextField.defaultProps = {
Vlad means this part

2024-07-21 10:06 UTC, erenfn requested changes

2024-07-21 10:06 UTC, erenfn commented on frontend/src/components/TextFieldComponents/CustomTextField/CustomTextField.jsx
> +  labelText,
Add these defaults here

  labelText: "",
  defaultValue: "",
  helperText: "",
  error: false,
  multiline: false,
  rows: 1,
  chips: [],
  startAdornment: null,
  endAdornment: null,
  placeholder: "",
  labelFontWeight: 600,
  TextFieldWidth: "100%",
  inputHeight: "56px",

2024-07-23 04:31 UTC, uparkalau approved these changes

2024-07-23 04:31 UTC, uparkalau approved these changes

2024-07-23 04:32 UTC, uparkalau approved these changes

2024-07-23 10:03 UTC, erenfn approved these changes

2024-07-23 14:25 UTC, merged