56 implementing user logout functionalities
bluewave-labs/bluewave-onboarding pull request #91
Opened 2024-07-02 07:55 UTC by uparkalau

2024-07-02 12:07 UTC, erenfn requested changes
I am still able to call add_popup (which requires a valid token) after I logout. I don't know if it is because an error in the logout function or authenticateJWT funcntion
Also can you please add example requests for forgot password and set new password?

2024-07-03 00:50 UTC, uparkalau commented
> I am still able to call add_popup (which requires a valid token) after I logout. I don't know if it is because an error in the logout function or authenticateJWT funcntion Also can you please add example requests for forgot password and set new password?
 This is not related to auth logic it is related to popup endpoints logic . This has to be new issue to resolve it.

2024-07-03 01:42 UTC, uparkalau commented
> > I am still able to call add_popup (which requires a valid token) after I logout. I don't know if it is because an error in the logout function or authenticateJWT funcntion Also can you please add example requests for forgot password and set new password?
> > This is not related to auth logic it is related to popup endpoints logic . This has to be new issue to resolve it.

i added logic to popup routes

2024-07-03 16:12 UTC, erenfn approved these changes

2024-07-04 19:39 UTC, merged