Feature/85-build-the-component-CreateActivityButton
bluewave-labs/bluewave-onboarding pull request #95
Opened 2024-07-03 15:56 UTC by rusisolanki

- Built the CreateActivityButton component
- Created CreateActivityButtonStyles.css file for custom CSS
- Built the CheckIcon component
- Made one change in the ButtonStyles.css file

2024-07-03 16:19 UTC, erenfn commented
You didn't commit your changes.

Also open pull request to develop, not to master

2024-07-03 16:20 UTC, erenfn requested changes
You didn't commit your changes.

Also open pull request to develop, not to master

2024-07-03 16:29 UTC, rusisolanki commented
Committed the changes

2024-07-03 16:32 UTC, erenfn commented
Check commits. The only commit you pushed is "[Merge remote-tracking branch 'origin/develop' into feature/85-build-t…]" which is a week ago

2024-07-03 16:56 UTC, erenfn submitted a review, later dismissed

2024-07-03 16:56 UTC, erenfn commented on package.json
> +{
Why do you have these outside the frontend folder?

2024-07-03 16:56 UTC, erenfn commented on .gitignore
> +node_modules
Why do you have these outside the frontend folder?

2024-07-03 16:56 UTC, erenfn commented on package-lock.json
remove gitignore package json and package lock json

2024-07-03 16:56 UTC, erenfn commented on frontend/src/components/CreateActivityButton/CreateActivityButton.jsx
> +  const listItems = [
Make list items a prop

2024-07-03 16:56 UTC, erenfn commented on frontend/src/components/CreateActivityButton/CreateActivityButton.jsx
> +        <h2 className="heading">Use banners to</h2>
make the heading a prop

2024-07-03 16:56 UTC, erenfn commented on frontend/src/components/Button/ButtonStyles.css
> +  /* width: 80px; */
"Can you change the width of the 'Button' without deleting this line? If not, can you modify Button.jsx to allow changing the style?"

2024-07-03 17:08 UTC, erenfn commented
you can create createActivityButtonData.js under data folder for listitems and heading for testing purposes

2024-07-06 09:08 UTC, swoopertr commented on frontend/src/components/CheckIcon/CheckIcon.jsx
> +export default function CheckIcon({ size, outline, color }) {
Please use the same pattern when created a components: 
this : export default function CheckIcon()
or this : const CreateActivityButton()

2024-07-06 09:08 UTC, swoopertr commented on frontend/src/components/CreateActivityButton/CreateActivityButton.jsx
> +const CreateActivityButton = ({ index }) => {
Please use the same pattern when created a components: 
this : export default function CheckIcon()
or this : const CreateActivityButton()

2024-07-06 23:19 UTC, uparkalau commented on frontend/src/components/CheckIcon/CheckIcon.jsx
> +CheckIcon.defaultProps = {
do not use defaultProps use default javascript parameters

2024-07-06 23:19 UTC, uparkalau commented on frontend/src/components/CheckIcon/CheckIcon.jsx
> +  color: "#7F56D9",
use constant for colors

2024-07-06 23:19 UTC, uparkalau commented on frontend/src/components/CheckIcon/CheckIcon.jsx
> +  color: PropTypes.oneOf(["#7F56D9", "#475467", "#079455"]),
use constant for colors

2024-07-06 23:20 UTC, uparkalau commented on frontend/src/components/CreateActivityButton/CreateActivityButton.jsx
> +        <Button text="Create a banner" className="button-primary-custom buttonStyle" />
it has to be parameter for button text.

2024-07-06 23:20 UTC, uparkalau commented on frontend/src/components/CreateActivityButton/CreateActivityButton.jsx
> +              <CheckIcon size='small' outline= {true} color='#7F56D9'/>
constant for colors

2024-07-06 23:23 UTC, uparkalau commented on frontend/src/components/CreateActivityButton/CreateActivityButton.jsx
> +  index: PropTypes.oneOf([0, 1, 2, 3, 4])
what is 0-4 ? use variables to understand what is it.

2024-07-06 23:23 UTC, uparkalau commented on frontend/src/components/CreateActivityButton/CreateActivityButton.jsx
> +CreateActivityButton.defaultProps = {
delete default props

2024-07-06 23:27 UTC, uparkalau commented on frontend/src/components/CheckIcon/CheckIcon.jsx
> +export default function CheckIcon({ size, outline, color }) {
Yes, please  use const CreateActivityButton() and arrow function.

2024-07-06 23:27 UTC, uparkalau commented on frontend/src/components/CreateActivityButton/CreateActivityButton.jsx
> +export default function CreateActivityButton({ index }){
const and arrow function

2024-07-06 23:29 UTC, uparkalau commented on frontend/src/components/Button/ButtonStyles.css
> +  /* width: 80px; */
resolve it as well

2024-07-06 23:30 UTC, uparkalau commented on frontend/src/components/CreateActivityButton/CreateActivityButton.jsx
> +          <h2 className="heading">{list[index].heading}</h2>
Please refactor it we do not need list and index here

2024-07-07 04:56 UTC, uparkalau commented on frontend/src/App.jsx
> +import CreateActivityButton from "./components/CreateActivityButton/CreateActivityButton";
Delete it if you don't use it

2024-07-07 05:41 UTC, uparkalau commented on frontend/src/components/CheckIcon/CheckIcon.jsx
> +const black = '#475467'
We have a global constant in a project.

2024-07-07 06:44 UTC, rusisolanki commented
> Check commits. The only commit you pushed is "[Merge remote-tracking branch 'origin/develop' into feature/85-build-t…]" which is a week ago

Done

2024-07-07 12:38 UTC, uparkalau commented on frontend/src/components/CreateActivityButton/CreateActivityButton.jsx
> +              <CheckIcon size='small' outline= {true} color='#7F56D9'/>
you still have color='#7F56D9'/> use colors constants that we use globally on the project

2024-07-07 12:42 UTC, uparkalau commented on frontend/src/components/CreateActivityButton/CreateActivityButton.jsx
> +        <Button text="Create a banner" className="button-primary-custom buttonStyle" />
<Button text="Create a banner" how to use it for other pages Tour and Popup and any other pages?

2024-07-07 13:18 UTC, uparkalau commented on frontend/src/components/CreateActivityButton/CreateActivityButton.jsx
> +const [hints, popups, banners, helperLinks, tours] = [0, 1, 2, 3, 4]
If you would like to use object use this style: "
const CreateActivity = ({ type, onClick }) => {
  const { heading, listItem, buttonText } = activityData[type];
"
Object example:

export const ACTIVITY_TYPES = {
  HINTS: 'hints',
  POPUPS: 'popups',
};

export const activityData = {
  [ACTIVITY_TYPES.HINTS]: {
    heading: 'Use hints to',
    listItem: [
      'Help user understand a complex situation',
      'Give contextual tips and tricks',
      'Give instant help',
    ],
    buttonText: 'Create a hint',
  },

CreateActivity.propTypes = {
  type: PropTypes.oneOf(Object.values(ACTIVITY_TYPES)).isRequired,
  onClick: PropTypes.func.isRequired,
};

<CreateActivity type={ACTIVITY_TYPES.HINTS} onClick={handleCreateHintClick} />

2024-07-07 13:23 UTC, uparkalau requested changes
this is my expectation with object implementation:
```

import React from 'react';
import PropTypes from 'prop-types';
import Button from '../Button/Button';
import CheckIcon from '../CheckIcon/CheckIcon';
import { ACTIVITY_TYPES, activityData } from '../../data/activityData';
import './CreateActivityStyles.css';

const CreateActivity = ({ type, onClick }) => {
  const { heading, listItem, buttonText } = activityData[type];

  return (
    <div className="create-activity-container">
      <div className="activity-contents">
        <h2 className="activity-heading">{heading}</h2>
        <ul className="activity-list">
          {listItem.map((item, idx) => (
            <li className="activity-list-item" key={idx}>
              <CheckIcon size="small" outline color="var(--primary-color)" />
              <span>{item}</span>
            </li>
          ))}
        </ul>
      </div>
      <Button text={buttonText} className="button-primary-custom activity-button" onClick={onClick} />
    </div>
  );
};

CreateActivity.propTypes = {
  type: PropTypes.oneOf(Object.values(ACTIVITY_TYPES)).isRequired,
  onClick: PropTypes.func.isRequired,
};

export default CreateActivity;
```

2024-07-09 06:47 UTC, uparkalau requested changes

2024-07-09 06:47 UTC, uparkalau commented on frontend/src/utils/constants.js
> +export const purple = "#7F56D9"
If you have any global colors use it from here or add it there.  src/styles/variables.css

2024-07-13 08:55 UTC, erenfn requested changes

2024-07-13 08:55 UTC, erenfn commented on frontend/src/components/CheckIcon/CheckIcon.jsx
> +import { purple, black, green } from "../../utils/constants";
Change this file too. You don't have these colors in constants

2024-07-13 08:55 UTC, erenfn commented on frontend/src/components/CheckIcon/CheckIcon.jsx
> +  color: PropTypes.oneOf([purple, black, green]),
same here

2024-07-13 08:55 UTC, erenfn commented on frontend/src/components/CreateActivityButton/CreateActivityButton.jsx
> +import '../../styles/variables.css'
import this in the css file not here

2024-07-13 08:55 UTC, erenfn commented on frontend/src/styles/variables.css
> +    --checkIcon-black: #475467;
We already have this color here (third text color)

2024-07-13 08:55 UTC, erenfn commented on frontend/src/components/CreateActivityButton/CreateActivityButtonStyles.css
> +    color: #344054;
use --main-text-color from variables.css

2024-07-13 08:55 UTC, erenfn commented on frontend/src/components/CreateActivityButton/CreateActivityButtonStyles.css
> +    color: #344054;
use --main-text-color from variables.css

2024-07-14 16:41 UTC, uparkalau submitted a review, later dismissed

2024-07-15 19:50 UTC, uparkalau approved these changes

2024-07-17 03:53 UTC, uparkalau approved these changes

2024-07-17 03:53 UTC, merged